// <copyright file="IConfiguration.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using TeslaFleetManagementApi.Standard.Authentication;

namespace TeslaFleetManagementApi.Standard
{
    /// <summary>
    /// IConfiguration.
    /// </summary>
    public interface IConfiguration
    {
        /// <summary>
        /// Gets Current API environment.
        /// </summary>
        Environment Environment { get; }

        /// <summary>
        /// Gets the credentials to use with Thirdpartytoken.
        /// </summary>
        IThirdpartytokenCredentials ThirdpartytokenCredentials { get; }

        /// <summary>
        /// Gets the credentials model to use with Thirdpartytoken.
        /// </summary>
        ThirdpartytokenModel ThirdpartytokenModel { get; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        string GetBaseUri(Server alias = Server.Default);
    }
}