// <copyright file="TeslaFleetManagementApiClient.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Authentication;
using APIMatic.Core.Utilities;
using APIMatic.Core.Utilities.Logger.Configuration;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using TeslaFleetManagementApi.Standard.Authentication;
using TeslaFleetManagementApi.Standard.Controllers;
using TeslaFleetManagementApi.Standard.Http.Client;
using TeslaFleetManagementApi.Standard.Logging;

namespace TeslaFleetManagementApi.Standard
{
    /// <summary>
    /// The gateway for the SDK. This class acts as a factory for Controller and
    /// holds the configuration of the SDK.
    /// </summary>
    public sealed class TeslaFleetManagementApiClient : IConfiguration
    {
        // A map of environments and their corresponding servers/baseurls
        private static readonly Dictionary<Environment, Dictionary<Enum, string>> EnvironmentsMap =
            new Dictionary<Environment, Dictionary<Enum, string>>
        {
            {
                Environment.Production, new Dictionary<Enum, string>
                {
                    { Server.Default, "https://fleet-api.prd.na.vn.cloud.tesla.com" },
                    { Server.AuthServer, "https://auth.tesla.com/oauth2/v3" },
                }
            },
        };

        private readonly GlobalConfiguration globalConfiguration;
        private SdkLoggingConfiguration sdkLoggingConfiguration;
        private const string userAgent = "DotNet SDK, Version: 1.0.4, on OS {os-info}";
        private readonly HttpCallback httpCallback;
        private readonly Lazy<ChargingController> charging;
        private readonly Lazy<EnergyController> energy;
        private readonly Lazy<PartnerController> partner;
        private readonly Lazy<UserController> user;
        private readonly Lazy<VehiclesController> vehicles;
        private readonly Lazy<VehicleCommandsController> vehicleCommands;
        private readonly Lazy<OAuthAuthorizationController> oAuthAuthorization;

        private TeslaFleetManagementApiClient(
            Environment environment,
            BearerAuthModel bearerAuthModel,
            ThirdpartytokenModel thirdpartytokenModel,
            HttpCallback httpCallback,
            IHttpClientConfiguration httpClientConfiguration,
            SdkLoggingConfiguration sdkLoggingConfiguration)
        {
            this.Environment = environment;
            this.httpCallback = httpCallback;
            this.HttpClientConfiguration = httpClientConfiguration;
            this.sdkLoggingConfiguration = sdkLoggingConfiguration;
            BearerAuthModel = bearerAuthModel;
            var bearerAuthManager = new BearerAuthManager(bearerAuthModel);
            ThirdpartytokenModel = thirdpartytokenModel;
            var thirdpartytokenManager = new ThirdpartytokenManager(thirdpartytokenModel,
                () => globalConfiguration,
                () => OAuthAuthorizationController);
            globalConfiguration = new GlobalConfiguration.Builder()
                .AuthManagers(new Dictionary<string, AuthManager> {
                    {"bearerAuth", bearerAuthManager},
                    {"thirdpartytoken", thirdpartytokenManager},
                })
                .ApiCallback(httpCallback)
                .HttpConfiguration(httpClientConfiguration)
                .ServerUrls(EnvironmentsMap[environment], Server.Default)
                .LoggingConfig(sdkLoggingConfiguration)
                .UserAgent(userAgent)
                .Build();
            BearerAuthCredentials = bearerAuthManager;
            ThirdpartytokenCredentials = thirdpartytokenManager;

            this.charging = new Lazy<ChargingController>(
                () => new ChargingController(globalConfiguration));
            this.energy = new Lazy<EnergyController>(
                () => new EnergyController(globalConfiguration));
            this.partner = new Lazy<PartnerController>(
                () => new PartnerController(globalConfiguration));
            this.user = new Lazy<UserController>(
                () => new UserController(globalConfiguration));
            this.vehicles = new Lazy<VehiclesController>(
                () => new VehiclesController(globalConfiguration));
            this.vehicleCommands = new Lazy<VehicleCommandsController>(
                () => new VehicleCommandsController(globalConfiguration));
            this.oAuthAuthorization = new Lazy<OAuthAuthorizationController>(
                () => new OAuthAuthorizationController(globalConfiguration));
        }

        /// <summary>
        /// Gets ChargingController controller.
        /// </summary>
        public ChargingController ChargingController => this.charging.Value;

        /// <summary>
        /// Gets EnergyController controller.
        /// </summary>
        public EnergyController EnergyController => this.energy.Value;

        /// <summary>
        /// Gets PartnerController controller.
        /// </summary>
        public PartnerController PartnerController => this.partner.Value;

        /// <summary>
        /// Gets UserController controller.
        /// </summary>
        public UserController UserController => this.user.Value;

        /// <summary>
        /// Gets VehiclesController controller.
        /// </summary>
        public VehiclesController VehiclesController => this.vehicles.Value;

        /// <summary>
        /// Gets VehicleCommandsController controller.
        /// </summary>
        public VehicleCommandsController VehicleCommandsController => this.vehicleCommands.Value;

        /// <summary>
        /// Gets OAuthAuthorizationController controller.
        /// </summary>
        public OAuthAuthorizationController OAuthAuthorizationController => this.oAuthAuthorization.Value;

        /// <summary>
        /// Gets the configuration of the Http Client associated with this client.
        /// </summary>
        public IHttpClientConfiguration HttpClientConfiguration { get; }

        /// <summary>
        /// Gets Environment.
        /// Current API environment.
        /// </summary>
        public Environment Environment { get; }

        /// <summary>
        /// Gets http callback.
        /// </summary>
        public HttpCallback HttpCallback => this.httpCallback;

        /// <summary>
        /// Gets the credentials to use with BearerAuth.
        /// </summary>
        public IBearerAuthCredentials BearerAuthCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with BearerAuth.
        /// </summary>
        public BearerAuthModel BearerAuthModel { get; private set; }

        /// <summary>
        /// Gets the access token to use with OAuth 2 authentication.
        /// </summary>
        public string AccessToken => this.BearerAuthCredentials.AccessToken;

        /// <summary>
        /// Gets the credentials to use with Thirdpartytoken.
        /// </summary>
        public IThirdpartytokenCredentials ThirdpartytokenCredentials { get; private set; }

        /// <summary>
        /// Gets the credentials model to use with Thirdpartytoken.
        /// </summary>
        public ThirdpartytokenModel ThirdpartytokenModel { get; private set; }

        /// <summary>
        /// Gets the URL for a particular alias in the current environment and appends
        /// it with template parameters.
        /// </summary>
        /// <param name="alias">Default value:DEFAULT.</param>
        /// <returns>Returns the baseurl.</returns>
        public string GetBaseUri(Server alias = Server.Default)
        {
            return globalConfiguration.ServerUrl(alias);
        }

        /// <summary>
        /// Creates an object of the TeslaFleetManagementApiClient using the values provided for the builder.
        /// </summary>
        /// <returns>Builder.</returns>
        public Builder ToBuilder()
        {
            Builder builder = new Builder()
                .Environment(this.Environment)
                .HttpCallback(httpCallback)
                .LoggingConfig(sdkLoggingConfiguration)
                .HttpClientConfig(config => config.Build());

            if (BearerAuthModel != null)
            {
                builder.BearerAuthCredentials(BearerAuthModel.ToBuilder().Build());
            }

            if (ThirdpartytokenModel != null)
            {
                builder.ThirdpartytokenCredentials(ThirdpartytokenModel.ToBuilder().Build());
            }

            return builder;
        }

        /// <inheritdoc/>
        public override string ToString()
        {
            return
                $"Environment = {this.Environment}, " +
                $"HttpClientConfiguration = {this.HttpClientConfiguration}, ";
        }

        /// <summary>
        /// Creates the client using builder.
        /// </summary>
        /// <returns> TeslaFleetManagementApiClient.</returns>
        internal static TeslaFleetManagementApiClient CreateFromEnvironment()
        {
            var builder = new Builder();

            string environment = System.Environment.GetEnvironmentVariable("TESLA_FLEET_MANAGEMENT_API_STANDARD_ENVIRONMENT");
            string accessToken = System.Environment.GetEnvironmentVariable("TESLA_FLEET_MANAGEMENT_API_STANDARD_ACCESS_TOKEN");
            string oAuthClientId = System.Environment.GetEnvironmentVariable("TESLA_FLEET_MANAGEMENT_API_STANDARD_O_AUTH_CLIENT_ID");
            string oAuthClientSecret = System.Environment.GetEnvironmentVariable("TESLA_FLEET_MANAGEMENT_API_STANDARD_O_AUTH_CLIENT_SECRET");
            string oAuthRedirectUri = System.Environment.GetEnvironmentVariable("TESLA_FLEET_MANAGEMENT_API_STANDARD_O_AUTH_REDIRECT_URI");

            if (environment != null)
            {
                builder.Environment(CoreHelper.JsonDeserialize<Environment>($"\"{environment}\""));
            }

            if (accessToken != null)
            {
                builder.BearerAuthCredentials(new BearerAuthModel
                .Builder(accessToken)
                .Build());
            }

            if (oAuthClientId != null && oAuthClientSecret != null && oAuthRedirectUri != null)
            {
                builder.ThirdpartytokenCredentials(new ThirdpartytokenModel
                .Builder(oAuthClientId, oAuthClientSecret, oAuthRedirectUri)
                .Build());
            }

            return builder.Build();
        }

        /// <summary>
        /// Creates the client from configuration.
        /// </summary>
        /// <returns> TeslaFleetManagementApiClient.</returns>
        public static TeslaFleetManagementApiClient FromConfiguration(IConfigurationSection configuration) =>
            Builder.FromConfiguration(configuration).Build();

        /// <summary>
        /// Builder class.
        /// </summary>
        public class Builder
        {
            private Environment _environment = TeslaFleetManagementApi.Standard.Environment.Production;
            private BearerAuthModel _bearerAuthModel = new BearerAuthModel();
            private ThirdpartytokenModel _thirdpartytokenModel = new ThirdpartytokenModel();
            private HttpClientConfiguration.Builder _httpClientConfig = new HttpClientConfiguration.Builder();
            private HttpCallback _httpCallback;
            private SdkLoggingConfiguration _sdkLoggingConfiguration;

            /// <summary>
            /// Sets credentials for BearerAuth.
            /// </summary>
            /// <param name="bearerAuthModel">BearerAuthModel.</param>
            /// <returns>Builder.</returns>
            public Builder BearerAuthCredentials(BearerAuthModel bearerAuthModel)
            {
                _bearerAuthModel = bearerAuthModel ??
                    throw new ArgumentNullException(nameof(bearerAuthModel));
                return this;
            }

            /// <summary>
            /// Sets credentials for Thirdpartytoken.
            /// </summary>
            /// <param name="thirdpartytokenModel">ThirdpartytokenModel.</param>
            /// <returns>Builder.</returns>
            public Builder ThirdpartytokenCredentials(ThirdpartytokenModel thirdpartytokenModel)
            {
                _thirdpartytokenModel = thirdpartytokenModel ??
                    throw new ArgumentNullException(nameof(thirdpartytokenModel));
                return this;
            }

            /// <summary>
            /// Sets Environment.
            /// </summary>
            /// <param name="environment"> Environment. </param>
            /// <returns> Builder. </returns>
            public Builder Environment(Environment environment)
            {
                _environment = environment;
                return this;
            }

            /// <summary>
            /// Sets HttpClientConfig.
            /// </summary>
            /// <param name="action"> Action. </param>
            /// <returns>Builder.</returns>
            public Builder HttpClientConfig(Action<HttpClientConfiguration.Builder> action)
            {
                if (action is null)
                {
                    throw new ArgumentNullException(nameof(action));
                }

                action(_httpClientConfig);
                return this;
            }

            private Builder HttpClientConfig(HttpClientConfiguration.Builder httpClientConfigurationBuilder)
            {
                if (httpClientConfigurationBuilder != null)
                {
                    _httpClientConfig = httpClientConfigurationBuilder;
                }

                return this;
            }

            /// <summary>
            /// Sets the default logging configuration, using the Console logger.
            /// </summary>
            /// <returns>Builder.</returns>
            public Builder LoggingConfig()
            {
                _sdkLoggingConfiguration = SdkLoggingConfiguration.Console();
                return this;
            }

            /// <summary>
            /// Sets the logging configuration using the provided <paramref name="action"/>.
            /// </summary>
            /// <param name="action">The action to perform on the logging configuration builder.</param>
            /// <returns>Builder.</returns>
            /// <exception cref="ArgumentNullException">Thrown when <paramref name="action"/> is null.</exception>
            public Builder LoggingConfig(Action<LogBuilder> action)
            {
                if (action is null) throw new ArgumentNullException(nameof(action));
                var logBuilder =
                    LogBuilder.CreateFromConfig(_sdkLoggingConfiguration ?? SdkLoggingConfiguration.Console());
                action(logBuilder);
                _sdkLoggingConfiguration = logBuilder.Build();
                return this;
            }

            internal Builder LoggingConfig(SdkLoggingConfiguration configuration)
            {
                _sdkLoggingConfiguration = configuration;
                return this;
            }

            /// <summary>
            /// Sets the HttpCallback for the Builder.
            /// </summary>
            /// <param name="httpCallback"> http callback. </param>
            /// <returns>Builder.</returns>
            public Builder HttpCallback(HttpCallback httpCallback)
            {
                _httpCallback = httpCallback;
                return this;
            }

            /// <summary>
            /// Creates an object of the TeslaFleetManagementApiClient using the values provided for the builder.
            /// </summary>
            /// <returns>TeslaFleetManagementApiClient.</returns>
            public TeslaFleetManagementApiClient Build()
            {
                if (_bearerAuthModel.AccessToken == null)
                {
                    _bearerAuthModel = null;
                }
                if (_thirdpartytokenModel.OAuthClientId == null || _thirdpartytokenModel.OAuthClientSecret == null || _thirdpartytokenModel.OAuthRedirectUri == null)
                {
                    _thirdpartytokenModel = null;
                }
                return new TeslaFleetManagementApiClient(
                    _environment,
                    _bearerAuthModel,
                    _thirdpartytokenModel,
                    _httpCallback,
                    _httpClientConfig.Build(),
                    _sdkLoggingConfiguration);
            }

            /// <summary>
            /// Creates the client builder from configuration.
            /// </summary>
            /// <returns> Builder.</returns>
            public static Builder FromConfiguration(IConfigurationSection config)
            {
                var builder = new Builder();
                var options = config.Get<TeslaFleetManagementApiClientOptions>();
                if (options == null) return builder;
                if (options.Environment != null)
                    builder.Environment(options.Environment.Value);
                if (options.BearerAuthCredentials != null)
                    builder.BearerAuthCredentials(BearerAuthModel.FromOptions(options.BearerAuthCredentials));
                if (options.ThirdpartytokenCredentials != null)
                    builder.ThirdpartytokenCredentials(ThirdpartytokenModel.FromOptions(options.ThirdpartytokenCredentials));
                if (options.HttpClientConfig != null)
                    builder.HttpClientConfig(Http.Client.HttpClientConfiguration.FromOptions(options.HttpClientConfig));
                if (options.LoggingConfig != null)
                    builder.LoggingConfig(LogBuilder.FromOptions(options.LoggingConfig));
                return builder;
            }
        }

        public class TeslaFleetManagementApiClientOptions
        {
            public Environment? Environment { get; set; }
            public BearerAuthModelOptions BearerAuthCredentials { get; set; }
            public ThirdpartytokenModelOptions ThirdpartytokenCredentials { get; set; }
            public HttpClientConfigurationOptions HttpClientConfig { get; set; }
            public LoggingConfigOptions LoggingConfig { get; set; }
        }
    }
}
