// <copyright file="OAuthAuthorizationController.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TeslaFleetManagementApi.Standard.Exceptions;
using TeslaFleetManagementApi.Standard.Http.Response;

namespace TeslaFleetManagementApi.Standard.Controllers
{
    /// <summary>
    /// OAuthAuthorizationController.
    /// </summary>
    public class OAuthAuthorizationController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OAuthAuthorizationController"/> class.
        /// </summary>
        internal OAuthAuthorizationController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Create a new OAuth 2 token.
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format.</param>
        /// <param name="code">Required parameter: Authorization Code.</param>
        /// <param name="redirectUri">Required parameter: Redirect Uri.</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint.</param>
        /// <returns>Returns the ApiResponse of Models.OAuthToken response from the API call.</returns>
        public ApiResponse<Models.OAuthToken> RequestTokenThirdpartytoken(
                string authorization,
                string code,
                string redirectUri,
                Dictionary<string, object> fieldParameters = null)
            => CoreHelper.RunTask(RequestTokenThirdpartytokenAsync(authorization, code, redirectUri, fieldParameters));

        /// <summary>
        /// Create a new OAuth 2 token.
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format.</param>
        /// <param name="code">Required parameter: Authorization Code.</param>
        /// <param name="redirectUri">Required parameter: Redirect Uri.</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.OAuthToken response from the API call.</returns>
        public async Task<ApiResponse<Models.OAuthToken>> RequestTokenThirdpartytokenAsync(
                string authorization,
                string code,
                string redirectUri,
                Dictionary<string, object> fieldParameters = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.OAuthToken>()
              .Server(Server.AuthServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/token")
                  .Parameters(parameters => parameters
                      .AdditionalForms(additionalForms => additionalForms.Setup(fieldParameters))
                      .Form(form => form.Setup("grant_type", "authorization_code"))
                      .Header(header => header.Setup("Authorization", authorization).Required())
                      .Form(form => form.Setup("code", code).Required())
                      .Form(form => form.Setup("redirect_uri", redirectUri).Required())))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("OAuth 2 provider returned an error.", (errorReason, context) => new OAuthProviderException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("OAuth 2 provider says client authentication failed.", (errorReason, context) => new OAuthProviderException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Obtain a new access token using a refresh token.
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format.</param>
        /// <param name="refreshToken">Required parameter: Refresh token.</param>
        /// <param name="scope">Optional parameter: Requested scopes as a space-delimited list..</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint.</param>
        /// <returns>Returns the ApiResponse of Models.OAuthToken response from the API call.</returns>
        public ApiResponse<Models.OAuthToken> RefreshTokenThirdpartytoken(
                string authorization,
                string refreshToken,
                string scope = null,
                Dictionary<string, object> fieldParameters = null)
            => CoreHelper.RunTask(RefreshTokenThirdpartytokenAsync(authorization, refreshToken, scope, fieldParameters));

        /// <summary>
        /// Obtain a new access token using a refresh token.
        /// </summary>
        /// <param name="authorization">Required parameter: Authorization header in Basic auth format.</param>
        /// <param name="refreshToken">Required parameter: Refresh token.</param>
        /// <param name="scope">Optional parameter: Requested scopes as a space-delimited list..</param>
        /// <param name="fieldParameters">Additional optional form parameters are supported by this endpoint.</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.OAuthToken response from the API call.</returns>
        public async Task<ApiResponse<Models.OAuthToken>> RefreshTokenThirdpartytokenAsync(
                string authorization,
                string refreshToken,
                string scope = null,
                Dictionary<string, object> fieldParameters = null,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.OAuthToken>()
              .Server(Server.AuthServer)
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/token")
                  .Parameters(parameters => parameters
                      .AdditionalForms(additionalForms => additionalForms.Setup(fieldParameters))
                      .Form(form => form.Setup("grant_type", "refresh_token"))
                      .Header(header => header.Setup("Authorization", authorization).Required())
                      .Form(form => form.Setup("refresh_token", refreshToken).Required())
                      .Form(form => form.Setup("scope", scope))))
              .ResponseHandler(responseHandler => responseHandler
                  .ErrorCase("400", CreateErrorCase("OAuth 2 provider returned an error.", (errorReason, context) => new OAuthProviderException(errorReason, context)))
                  .ErrorCase("401", CreateErrorCase("OAuth 2 provider says client authentication failed.", (errorReason, context) => new OAuthProviderException(errorReason, context))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}