// <copyright file="VehicleCommandsController.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core;
using APIMatic.Core.Utilities;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using TeslaFleetManagementApi.Standard.Http.Response;

namespace TeslaFleetManagementApi.Standard.Controllers
{
    /// <summary>
    /// VehicleCommandsController.
    /// </summary>
    public class VehicleCommandsController : BaseController
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleCommandsController"/> class.
        /// </summary>
        internal VehicleCommandsController(GlobalConfiguration globalConfiguration) : base(globalConfiguration) { }

        /// <summary>
        /// Controls the front or rear trunk.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> ActuateTrunk(
                string vehicleTag,
                Models.ActuateTrunkRequest body)
            => CoreHelper.RunTask(ActuateTrunkAsync(vehicleTag, body));

        /// <summary>
        /// Controls the front or rear trunk.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> ActuateTrunkAsync(
                string vehicleTag,
                Models.ActuateTrunkRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/actuate_trunk")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Add charge schedule EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> AddChargeSchedule(
                string vehicleTag,
                Models.AddChargeScheduleRequest body)
            => CoreHelper.RunTask(AddChargeScheduleAsync(vehicleTag, body));

        /// <summary>
        /// Add charge schedule EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> AddChargeScheduleAsync(
                string vehicleTag,
                Models.AddChargeScheduleRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/add_charge_schedule")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Add precondition schedule EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> AddPreconditionSchedule(
                string vehicleTag,
                Models.AddPreconditionScheduleRequest body)
            => CoreHelper.RunTask(AddPreconditionScheduleAsync(vehicleTag, body));

        /// <summary>
        /// Add precondition schedule EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> AddPreconditionScheduleAsync(
                string vehicleTag,
                Models.AddPreconditionScheduleRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/add_precondition_schedule")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Adjust media volume EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> AdjustMediaVolume(
                string vehicleTag,
                Models.AdjustVolumeRequest body)
            => CoreHelper.RunTask(AdjustMediaVolumeAsync(vehicleTag, body));

        /// <summary>
        /// Adjust media volume EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> AdjustMediaVolumeAsync(
                string vehicleTag,
                Models.AdjustVolumeRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/adjust_volume")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Start climate preconditioning EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> StartClimatePreconditioning(
                string vehicleTag)
            => CoreHelper.RunTask(StartClimatePreconditioningAsync(vehicleTag));

        /// <summary>
        /// Start climate preconditioning EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> StartClimatePreconditioningAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/auto_conditioning_start")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Stop climate preconditioning EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> StopClimatePreconditioning(
                string vehicleTag)
            => CoreHelper.RunTask(StopClimatePreconditioningAsync(vehicleTag));

        /// <summary>
        /// Stop climate preconditioning EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> StopClimatePreconditioningAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/auto_conditioning_stop")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Cancel software update EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> CancelSoftwareUpdate(
                string vehicleTag)
            => CoreHelper.RunTask(CancelSoftwareUpdateAsync(vehicleTag));

        /// <summary>
        /// Cancel software update EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> CancelSoftwareUpdateAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/cancel_software_update")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Charge max range EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> ChargeMaxRange(
                string vehicleTag)
            => CoreHelper.RunTask(ChargeMaxRangeAsync(vehicleTag));

        /// <summary>
        /// Charge max range EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> ChargeMaxRangeAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/charge_max_range")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Open charge port door EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> OpenChargePortDoor(
                string vehicleTag)
            => CoreHelper.RunTask(OpenChargePortDoorAsync(vehicleTag));

        /// <summary>
        /// Open charge port door EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> OpenChargePortDoorAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/charge_port_door_open")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Close charge port door EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> CloseChargePortDoor(
                string vehicleTag)
            => CoreHelper.RunTask(CloseChargePortDoorAsync(vehicleTag));

        /// <summary>
        /// Close charge port door EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> CloseChargePortDoorAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/charge_port_door_close")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Charge standard EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> ChargeStandard(
                string vehicleTag)
            => CoreHelper.RunTask(ChargeStandardAsync(vehicleTag));

        /// <summary>
        /// Charge standard EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> ChargeStandardAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/charge_standard")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Start charging EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> StartCharging(
                string vehicleTag)
            => CoreHelper.RunTask(StartChargingAsync(vehicleTag));

        /// <summary>
        /// Start charging EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> StartChargingAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/charge_start")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Stop charging EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> StopCharging(
                string vehicleTag)
            => CoreHelper.RunTask(StopChargingAsync(vehicleTag));

        /// <summary>
        /// Stop charging EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> StopChargingAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/charge_stop")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Deactivates PIN to Drive and resets the associated PIN for supported firmware versions.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> ClearPinToDriveAdmin(
                string vehicleTag)
            => CoreHelper.RunTask(ClearPinToDriveAdminAsync(vehicleTag));

        /// <summary>
        /// Deactivates PIN to Drive and resets the associated PIN for supported firmware versions.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> ClearPinToDriveAdminAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/clear_pin_to_drive_admin")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Lock doors EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> LockDoors(
                string vehicleTag)
            => CoreHelper.RunTask(LockDoorsAsync(vehicleTag));

        /// <summary>
        /// Lock doors EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> LockDoorsAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/door_lock")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Unlock doors EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> UnlockDoors(
                string vehicleTag)
            => CoreHelper.RunTask(UnlockDoorsAsync(vehicleTag));

        /// <summary>
        /// Unlock doors EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> UnlockDoorsAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/door_unlock")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Erases user data from the vehicle UI. Requires Guest Mode.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> EraseUserData(
                string vehicleTag)
            => CoreHelper.RunTask(EraseUserDataAsync(vehicleTag));

        /// <summary>
        /// Erases user data from the vehicle UI. Requires Guest Mode.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> EraseUserDataAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/erase_user_data")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Briefly flashes vehicle headlights.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> FlashLights(
                string vehicleTag)
            => CoreHelper.RunTask(FlashLightsAsync(vehicleTag));

        /// <summary>
        /// Briefly flashes vehicle headlights.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> FlashLightsAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/flash_lights")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Enable or disable Guest Mode EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> EnableOrDisableGuestMode(
                string vehicleTag,
                Models.GuestModeRequest body)
            => CoreHelper.RunTask(EnableOrDisableGuestModeAsync(vehicleTag, body));

        /// <summary>
        /// Enable or disable Guest Mode EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="body">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> EnableOrDisableGuestModeAsync(
                string vehicleTag,
                Models.GuestModeRequest body,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/guest_mode")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Body(b => b.Setup(body).Required())
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())
                      .Header(header => header.Setup("Content-Type", "application/json"))))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Honk horn EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> HonkHorn(
                string vehicleTag)
            => CoreHelper.RunTask(HonkHornAsync(vehicleTag));

        /// <summary>
        /// Honk horn EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> HonkHornAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/honk_horn")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);

        /// <summary>
        /// Next favorite media track EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public ApiResponse<Models.CommandResponse> NextFavoriteMediaTrack(
                string vehicleTag)
            => CoreHelper.RunTask(NextFavoriteMediaTrackAsync(vehicleTag));

        /// <summary>
        /// Next favorite media track EndPoint.
        /// </summary>
        /// <param name="vehicleTag">Required parameter: .</param>
        /// <param name="cancellationToken"> cancellationToken. </param>
        /// <returns>Returns the ApiResponse of Models.CommandResponse response from the API call.</returns>
        public async Task<ApiResponse<Models.CommandResponse>> NextFavoriteMediaTrackAsync(
                string vehicleTag,
                CancellationToken cancellationToken = default)
            => await CreateApiCall<Models.CommandResponse>()
              .RequestBuilder(requestBuilder => requestBuilder
                  .Setup(HttpMethod.Post, "/api/1/vehicles/{vehicle_tag}/command/media_next_fav")
                  .WithAuth("thirdpartytoken")
                  .Parameters(parameters => parameters
                      .Template(template => template.Setup("vehicle_tag", vehicleTag).Required())))
              .ExecuteAsync(cancellationToken).ConfigureAwait(false);
    }
}