// <copyright file="AddPreconditionScheduleRequest.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// AddPreconditionScheduleRequest.
    /// </summary>
    public class AddPreconditionScheduleRequest
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AddPreconditionScheduleRequest"/> class.
        /// </summary>
        public AddPreconditionScheduleRequest()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AddPreconditionScheduleRequest"/> class.
        /// </summary>
        /// <param name="lat">lat.</param>
        /// <param name="lon">lon.</param>
        /// <param name="id">id.</param>
        /// <param name="enabled">enabled.</param>
        /// <param name="daysOfWeek">days_of_week.</param>
        /// <param name="preconditionTime">precondition_time.</param>
        /// <param name="oneTime">one_time.</param>
        public AddPreconditionScheduleRequest(
            double lat,
            double lon,
            int id,
            bool enabled,
            string daysOfWeek = null,
            int? preconditionTime = null,
            bool? oneTime = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Lat = lat;
            this.Lon = lon;
            this.Id = id;
            this.DaysOfWeek = daysOfWeek;
            this.PreconditionTime = preconditionTime;
            this.OneTime = oneTime;
            this.Enabled = enabled;
        }

        /// <summary>
        /// Gets or sets Lat.
        /// </summary>
        [JsonProperty("lat")]
        public double Lat { get; set; }

        /// <summary>
        /// Gets or sets Lon.
        /// </summary>
        [JsonProperty("lon")]
        public double Lon { get; set; }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or sets DaysOfWeek.
        /// </summary>
        [JsonProperty("days_of_week", NullValueHandling = NullValueHandling.Ignore)]
        public string DaysOfWeek { get; set; }

        /// <summary>
        /// Gets or sets PreconditionTime.
        /// </summary>
        [JsonProperty("precondition_time", NullValueHandling = NullValueHandling.Ignore)]
        public int? PreconditionTime { get; set; }

        /// <summary>
        /// Gets or sets OneTime.
        /// </summary>
        [JsonProperty("one_time", NullValueHandling = NullValueHandling.Ignore)]
        public bool? OneTime { get; set; }

        /// <summary>
        /// Gets or sets Enabled.
        /// </summary>
        [JsonProperty("enabled")]
        public bool Enabled { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"AddPreconditionScheduleRequest : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is AddPreconditionScheduleRequest other &&
                (this.Lat.Equals(other.Lat)) &&
                (this.Lon.Equals(other.Lon)) &&
                (this.Id.Equals(other.Id)) &&
                (this.DaysOfWeek == null && other.DaysOfWeek == null ||
                 this.DaysOfWeek?.Equals(other.DaysOfWeek) == true) &&
                (this.PreconditionTime == null && other.PreconditionTime == null ||
                 this.PreconditionTime?.Equals(other.PreconditionTime) == true) &&
                (this.OneTime == null && other.OneTime == null ||
                 this.OneTime?.Equals(other.OneTime) == true) &&
                (this.Enabled.Equals(other.Enabled)) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Lat = {this.Lat}");
            toStringOutput.Add($"Lon = {this.Lon}");
            toStringOutput.Add($"Id = {this.Id}");
            toStringOutput.Add($"DaysOfWeek = {this.DaysOfWeek ?? "null"}");
            toStringOutput.Add($"PreconditionTime = {(this.PreconditionTime == null ? "null" : this.PreconditionTime.ToString())}");
            toStringOutput.Add($"OneTime = {(this.OneTime == null ? "null" : this.OneTime.ToString())}");
            toStringOutput.Add($"Enabled = {this.Enabled}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}