// <copyright file="ChargingFee.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ChargingFee.
    /// </summary>
    public class ChargingFee
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private double? rateTier3;
        private double? rateTier4;
        private double? usageTier3;
        private double? usageTier4;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "rateTier3", false },
            { "rateTier4", false },
            { "usageTier3", false },
            { "usageTier4", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingFee"/> class.
        /// </summary>
        public ChargingFee()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingFee"/> class.
        /// </summary>
        /// <param name="sessionFeeId">sessionFeeId.</param>
        /// <param name="feeType">feeType.</param>
        /// <param name="currencyCode">currencyCode.</param>
        /// <param name="pricingType">pricingType.</param>
        /// <param name="rateBase">rateBase.</param>
        /// <param name="rateTier1">rateTier1.</param>
        /// <param name="rateTier2">rateTier2.</param>
        /// <param name="rateTier3">rateTier3.</param>
        /// <param name="rateTier4">rateTier4.</param>
        /// <param name="usageBase">usageBase.</param>
        /// <param name="usageTier1">usageTier1.</param>
        /// <param name="usageTier2">usageTier2.</param>
        /// <param name="usageTier3">usageTier3.</param>
        /// <param name="usageTier4">usageTier4.</param>
        /// <param name="totalBase">totalBase.</param>
        /// <param name="totalTier1">totalTier1.</param>
        /// <param name="totalTier2">totalTier2.</param>
        /// <param name="totalTier3">totalTier3.</param>
        /// <param name="totalTier4">totalTier4.</param>
        /// <param name="totalDue">totalDue.</param>
        /// <param name="netDue">netDue.</param>
        /// <param name="uom">uom.</param>
        /// <param name="isPaid">isPaid.</param>
        /// <param name="status">status.</param>
        public ChargingFee(
            int? sessionFeeId = null,
            string feeType = null,
            string currencyCode = null,
            string pricingType = null,
            double? rateBase = null,
            double? rateTier1 = null,
            double? rateTier2 = null,
            double? rateTier3 = null,
            double? rateTier4 = null,
            double? usageBase = null,
            double? usageTier1 = null,
            double? usageTier2 = null,
            double? usageTier3 = null,
            double? usageTier4 = null,
            double? totalBase = null,
            double? totalTier1 = null,
            double? totalTier2 = null,
            double? totalTier3 = null,
            double? totalTier4 = null,
            double? totalDue = null,
            double? netDue = null,
            string uom = null,
            bool? isPaid = null,
            string status = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.SessionFeeId = sessionFeeId;
            this.FeeType = feeType;
            this.CurrencyCode = currencyCode;
            this.PricingType = pricingType;
            this.RateBase = rateBase;
            this.RateTier1 = rateTier1;
            this.RateTier2 = rateTier2;

            if (rateTier3 != null)
            {
                this.RateTier3 = rateTier3;
            }

            if (rateTier4 != null)
            {
                this.RateTier4 = rateTier4;
            }
            this.UsageBase = usageBase;
            this.UsageTier1 = usageTier1;
            this.UsageTier2 = usageTier2;

            if (usageTier3 != null)
            {
                this.UsageTier3 = usageTier3;
            }

            if (usageTier4 != null)
            {
                this.UsageTier4 = usageTier4;
            }
            this.TotalBase = totalBase;
            this.TotalTier1 = totalTier1;
            this.TotalTier2 = totalTier2;
            this.TotalTier3 = totalTier3;
            this.TotalTier4 = totalTier4;
            this.TotalDue = totalDue;
            this.NetDue = netDue;
            this.Uom = uom;
            this.IsPaid = isPaid;
            this.Status = status;
        }

        /// <summary>
        /// Gets or sets SessionFeeId.
        /// </summary>
        [JsonProperty("sessionFeeId", NullValueHandling = NullValueHandling.Ignore)]
        public int? SessionFeeId { get; set; }

        /// <summary>
        /// Gets or sets FeeType.
        /// </summary>
        [JsonProperty("feeType", NullValueHandling = NullValueHandling.Ignore)]
        public string FeeType { get; set; }

        /// <summary>
        /// Gets or sets CurrencyCode.
        /// </summary>
        [JsonProperty("currencyCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CurrencyCode { get; set; }

        /// <summary>
        /// Gets or sets PricingType.
        /// </summary>
        [JsonProperty("pricingType", NullValueHandling = NullValueHandling.Ignore)]
        public string PricingType { get; set; }

        /// <summary>
        /// Gets or sets RateBase.
        /// </summary>
        [JsonProperty("rateBase", NullValueHandling = NullValueHandling.Ignore)]
        public double? RateBase { get; set; }

        /// <summary>
        /// Gets or sets RateTier1.
        /// </summary>
        [JsonProperty("rateTier1", NullValueHandling = NullValueHandling.Ignore)]
        public double? RateTier1 { get; set; }

        /// <summary>
        /// Gets or sets RateTier2.
        /// </summary>
        [JsonProperty("rateTier2", NullValueHandling = NullValueHandling.Ignore)]
        public double? RateTier2 { get; set; }

        /// <summary>
        /// Gets or sets RateTier3.
        /// </summary>
        [JsonProperty("rateTier3")]
        public double? RateTier3
        {
            get
            {
                return this.rateTier3;
            }

            set
            {
                this.shouldSerialize["rateTier3"] = true;
                this.rateTier3 = value;
            }
        }

        /// <summary>
        /// Gets or sets RateTier4.
        /// </summary>
        [JsonProperty("rateTier4")]
        public double? RateTier4
        {
            get
            {
                return this.rateTier4;
            }

            set
            {
                this.shouldSerialize["rateTier4"] = true;
                this.rateTier4 = value;
            }
        }

        /// <summary>
        /// Gets or sets UsageBase.
        /// </summary>
        [JsonProperty("usageBase", NullValueHandling = NullValueHandling.Ignore)]
        public double? UsageBase { get; set; }

        /// <summary>
        /// Gets or sets UsageTier1.
        /// </summary>
        [JsonProperty("usageTier1", NullValueHandling = NullValueHandling.Ignore)]
        public double? UsageTier1 { get; set; }

        /// <summary>
        /// Gets or sets UsageTier2.
        /// </summary>
        [JsonProperty("usageTier2", NullValueHandling = NullValueHandling.Ignore)]
        public double? UsageTier2 { get; set; }

        /// <summary>
        /// Gets or sets UsageTier3.
        /// </summary>
        [JsonProperty("usageTier3")]
        public double? UsageTier3
        {
            get
            {
                return this.usageTier3;
            }

            set
            {
                this.shouldSerialize["usageTier3"] = true;
                this.usageTier3 = value;
            }
        }

        /// <summary>
        /// Gets or sets UsageTier4.
        /// </summary>
        [JsonProperty("usageTier4")]
        public double? UsageTier4
        {
            get
            {
                return this.usageTier4;
            }

            set
            {
                this.shouldSerialize["usageTier4"] = true;
                this.usageTier4 = value;
            }
        }

        /// <summary>
        /// Gets or sets TotalBase.
        /// </summary>
        [JsonProperty("totalBase", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalBase { get; set; }

        /// <summary>
        /// Gets or sets TotalTier1.
        /// </summary>
        [JsonProperty("totalTier1", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalTier1 { get; set; }

        /// <summary>
        /// Gets or sets TotalTier2.
        /// </summary>
        [JsonProperty("totalTier2", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalTier2 { get; set; }

        /// <summary>
        /// Gets or sets TotalTier3.
        /// </summary>
        [JsonProperty("totalTier3", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalTier3 { get; set; }

        /// <summary>
        /// Gets or sets TotalTier4.
        /// </summary>
        [JsonProperty("totalTier4", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalTier4 { get; set; }

        /// <summary>
        /// Gets or sets TotalDue.
        /// </summary>
        [JsonProperty("totalDue", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalDue { get; set; }

        /// <summary>
        /// Gets or sets NetDue.
        /// </summary>
        [JsonProperty("netDue", NullValueHandling = NullValueHandling.Ignore)]
        public double? NetDue { get; set; }

        /// <summary>
        /// Gets or sets Uom.
        /// </summary>
        [JsonProperty("uom", NullValueHandling = NullValueHandling.Ignore)]
        public string Uom { get; set; }

        /// <summary>
        /// Gets or sets IsPaid.
        /// </summary>
        [JsonProperty("isPaid", NullValueHandling = NullValueHandling.Ignore)]
        public bool? IsPaid { get; set; }

        /// <summary>
        /// Gets or sets Status.
        /// </summary>
        [JsonProperty("status", NullValueHandling = NullValueHandling.Ignore)]
        public string Status { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargingFee : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRateTier3()
        {
            this.shouldSerialize["rateTier3"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetRateTier4()
        {
            this.shouldSerialize["rateTier4"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUsageTier3()
        {
            this.shouldSerialize["usageTier3"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetUsageTier4()
        {
            this.shouldSerialize["usageTier4"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRateTier3()
        {
            return this.shouldSerialize["rateTier3"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeRateTier4()
        {
            return this.shouldSerialize["rateTier4"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUsageTier3()
        {
            return this.shouldSerialize["usageTier3"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeUsageTier4()
        {
            return this.shouldSerialize["usageTier4"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargingFee other &&
                (this.SessionFeeId == null && other.SessionFeeId == null ||
                 this.SessionFeeId?.Equals(other.SessionFeeId) == true) &&
                (this.FeeType == null && other.FeeType == null ||
                 this.FeeType?.Equals(other.FeeType) == true) &&
                (this.CurrencyCode == null && other.CurrencyCode == null ||
                 this.CurrencyCode?.Equals(other.CurrencyCode) == true) &&
                (this.PricingType == null && other.PricingType == null ||
                 this.PricingType?.Equals(other.PricingType) == true) &&
                (this.RateBase == null && other.RateBase == null ||
                 this.RateBase?.Equals(other.RateBase) == true) &&
                (this.RateTier1 == null && other.RateTier1 == null ||
                 this.RateTier1?.Equals(other.RateTier1) == true) &&
                (this.RateTier2 == null && other.RateTier2 == null ||
                 this.RateTier2?.Equals(other.RateTier2) == true) &&
                (this.RateTier3 == null && other.RateTier3 == null ||
                 this.RateTier3?.Equals(other.RateTier3) == true) &&
                (this.RateTier4 == null && other.RateTier4 == null ||
                 this.RateTier4?.Equals(other.RateTier4) == true) &&
                (this.UsageBase == null && other.UsageBase == null ||
                 this.UsageBase?.Equals(other.UsageBase) == true) &&
                (this.UsageTier1 == null && other.UsageTier1 == null ||
                 this.UsageTier1?.Equals(other.UsageTier1) == true) &&
                (this.UsageTier2 == null && other.UsageTier2 == null ||
                 this.UsageTier2?.Equals(other.UsageTier2) == true) &&
                (this.UsageTier3 == null && other.UsageTier3 == null ||
                 this.UsageTier3?.Equals(other.UsageTier3) == true) &&
                (this.UsageTier4 == null && other.UsageTier4 == null ||
                 this.UsageTier4?.Equals(other.UsageTier4) == true) &&
                (this.TotalBase == null && other.TotalBase == null ||
                 this.TotalBase?.Equals(other.TotalBase) == true) &&
                (this.TotalTier1 == null && other.TotalTier1 == null ||
                 this.TotalTier1?.Equals(other.TotalTier1) == true) &&
                (this.TotalTier2 == null && other.TotalTier2 == null ||
                 this.TotalTier2?.Equals(other.TotalTier2) == true) &&
                (this.TotalTier3 == null && other.TotalTier3 == null ||
                 this.TotalTier3?.Equals(other.TotalTier3) == true) &&
                (this.TotalTier4 == null && other.TotalTier4 == null ||
                 this.TotalTier4?.Equals(other.TotalTier4) == true) &&
                (this.TotalDue == null && other.TotalDue == null ||
                 this.TotalDue?.Equals(other.TotalDue) == true) &&
                (this.NetDue == null && other.NetDue == null ||
                 this.NetDue?.Equals(other.NetDue) == true) &&
                (this.Uom == null && other.Uom == null ||
                 this.Uom?.Equals(other.Uom) == true) &&
                (this.IsPaid == null && other.IsPaid == null ||
                 this.IsPaid?.Equals(other.IsPaid) == true) &&
                (this.Status == null && other.Status == null ||
                 this.Status?.Equals(other.Status) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SessionFeeId = {(this.SessionFeeId == null ? "null" : this.SessionFeeId.ToString())}");
            toStringOutput.Add($"FeeType = {this.FeeType ?? "null"}");
            toStringOutput.Add($"CurrencyCode = {this.CurrencyCode ?? "null"}");
            toStringOutput.Add($"PricingType = {this.PricingType ?? "null"}");
            toStringOutput.Add($"RateBase = {(this.RateBase == null ? "null" : this.RateBase.ToString())}");
            toStringOutput.Add($"RateTier1 = {(this.RateTier1 == null ? "null" : this.RateTier1.ToString())}");
            toStringOutput.Add($"RateTier2 = {(this.RateTier2 == null ? "null" : this.RateTier2.ToString())}");
            toStringOutput.Add($"RateTier3 = {(this.RateTier3 == null ? "null" : this.RateTier3.ToString())}");
            toStringOutput.Add($"RateTier4 = {(this.RateTier4 == null ? "null" : this.RateTier4.ToString())}");
            toStringOutput.Add($"UsageBase = {(this.UsageBase == null ? "null" : this.UsageBase.ToString())}");
            toStringOutput.Add($"UsageTier1 = {(this.UsageTier1 == null ? "null" : this.UsageTier1.ToString())}");
            toStringOutput.Add($"UsageTier2 = {(this.UsageTier2 == null ? "null" : this.UsageTier2.ToString())}");
            toStringOutput.Add($"UsageTier3 = {(this.UsageTier3 == null ? "null" : this.UsageTier3.ToString())}");
            toStringOutput.Add($"UsageTier4 = {(this.UsageTier4 == null ? "null" : this.UsageTier4.ToString())}");
            toStringOutput.Add($"TotalBase = {(this.TotalBase == null ? "null" : this.TotalBase.ToString())}");
            toStringOutput.Add($"TotalTier1 = {(this.TotalTier1 == null ? "null" : this.TotalTier1.ToString())}");
            toStringOutput.Add($"TotalTier2 = {(this.TotalTier2 == null ? "null" : this.TotalTier2.ToString())}");
            toStringOutput.Add($"TotalTier3 = {(this.TotalTier3 == null ? "null" : this.TotalTier3.ToString())}");
            toStringOutput.Add($"TotalTier4 = {(this.TotalTier4 == null ? "null" : this.TotalTier4.ToString())}");
            toStringOutput.Add($"TotalDue = {(this.TotalDue == null ? "null" : this.TotalDue.ToString())}");
            toStringOutput.Add($"NetDue = {(this.NetDue == null ? "null" : this.NetDue.ToString())}");
            toStringOutput.Add($"Uom = {this.Uom ?? "null"}");
            toStringOutput.Add($"IsPaid = {(this.IsPaid == null ? "null" : this.IsPaid.ToString())}");
            toStringOutput.Add($"Status = {this.Status ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}