// <copyright file="ChargingLocation.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ChargingLocation.
    /// </summary>
    public class ChargingLocation
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingLocation"/> class.
        /// </summary>
        public ChargingLocation()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingLocation"/> class.
        /// </summary>
        /// <param name="name">name.</param>
        /// <param name="type">type.</param>
        /// <param name="distanceMiles">distance_miles.</param>
        /// <param name="amenities">amenities.</param>
        /// <param name="availableStalls">available_stalls.</param>
        /// <param name="totalStalls">total_stalls.</param>
        /// <param name="siteClosed">site_closed.</param>
        /// <param name="billingInfo">billing_info.</param>
        /// <param name="location">location.</param>
        public ChargingLocation(
            string name = null,
            string type = null,
            double? distanceMiles = null,
            string amenities = null,
            int? availableStalls = null,
            int? totalStalls = null,
            bool? siteClosed = null,
            string billingInfo = null,
            Models.Location1 location = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Name = name;
            this.Type = type;
            this.DistanceMiles = distanceMiles;
            this.Amenities = amenities;
            this.AvailableStalls = availableStalls;
            this.TotalStalls = totalStalls;
            this.SiteClosed = siteClosed;
            this.BillingInfo = billingInfo;
            this.Location = location;
        }

        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        [JsonProperty("name", NullValueHandling = NullValueHandling.Ignore)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets Type.
        /// </summary>
        [JsonProperty("type", NullValueHandling = NullValueHandling.Ignore)]
        public string Type { get; set; }

        /// <summary>
        /// Gets or sets DistanceMiles.
        /// </summary>
        [JsonProperty("distance_miles", NullValueHandling = NullValueHandling.Ignore)]
        public double? DistanceMiles { get; set; }

        /// <summary>
        /// Gets or sets Amenities.
        /// </summary>
        [JsonProperty("amenities", NullValueHandling = NullValueHandling.Ignore)]
        public string Amenities { get; set; }

        /// <summary>
        /// Gets or sets AvailableStalls.
        /// </summary>
        [JsonProperty("available_stalls", NullValueHandling = NullValueHandling.Ignore)]
        public int? AvailableStalls { get; set; }

        /// <summary>
        /// Gets or sets TotalStalls.
        /// </summary>
        [JsonProperty("total_stalls", NullValueHandling = NullValueHandling.Ignore)]
        public int? TotalStalls { get; set; }

        /// <summary>
        /// Gets or sets SiteClosed.
        /// </summary>
        [JsonProperty("site_closed", NullValueHandling = NullValueHandling.Ignore)]
        public bool? SiteClosed { get; set; }

        /// <summary>
        /// Gets or sets BillingInfo.
        /// </summary>
        [JsonProperty("billing_info", NullValueHandling = NullValueHandling.Ignore)]
        public string BillingInfo { get; set; }

        /// <summary>
        /// Gets or sets Location.
        /// </summary>
        [JsonProperty("location", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Location1 Location { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargingLocation : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargingLocation other &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.Type == null && other.Type == null ||
                 this.Type?.Equals(other.Type) == true) &&
                (this.DistanceMiles == null && other.DistanceMiles == null ||
                 this.DistanceMiles?.Equals(other.DistanceMiles) == true) &&
                (this.Amenities == null && other.Amenities == null ||
                 this.Amenities?.Equals(other.Amenities) == true) &&
                (this.AvailableStalls == null && other.AvailableStalls == null ||
                 this.AvailableStalls?.Equals(other.AvailableStalls) == true) &&
                (this.TotalStalls == null && other.TotalStalls == null ||
                 this.TotalStalls?.Equals(other.TotalStalls) == true) &&
                (this.SiteClosed == null && other.SiteClosed == null ||
                 this.SiteClosed?.Equals(other.SiteClosed) == true) &&
                (this.BillingInfo == null && other.BillingInfo == null ||
                 this.BillingInfo?.Equals(other.BillingInfo) == true) &&
                (this.Location == null && other.Location == null ||
                 this.Location?.Equals(other.Location) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Type = {this.Type ?? "null"}");
            toStringOutput.Add($"DistanceMiles = {(this.DistanceMiles == null ? "null" : this.DistanceMiles.ToString())}");
            toStringOutput.Add($"Amenities = {this.Amenities ?? "null"}");
            toStringOutput.Add($"AvailableStalls = {(this.AvailableStalls == null ? "null" : this.AvailableStalls.ToString())}");
            toStringOutput.Add($"TotalStalls = {(this.TotalStalls == null ? "null" : this.TotalStalls.ToString())}");
            toStringOutput.Add($"SiteClosed = {(this.SiteClosed == null ? "null" : this.SiteClosed.ToString())}");
            toStringOutput.Add($"BillingInfo = {this.BillingInfo ?? "null"}");
            toStringOutput.Add($"Location = {(this.Location == null ? "null" : this.Location.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}