// <copyright file="ChargingInvoice.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ChargingInvoice.
    /// </summary>
    public class ChargingInvoice
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingInvoice"/> class.
        /// </summary>
        public ChargingInvoice()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingInvoice"/> class.
        /// </summary>
        /// <param name="fileName">fileName.</param>
        /// <param name="contentId">contentId.</param>
        /// <param name="invoiceType">invoiceType.</param>
        public ChargingInvoice(
            string fileName = null,
            string contentId = null,
            string invoiceType = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.FileName = fileName;
            this.ContentId = contentId;
            this.InvoiceType = invoiceType;
        }

        /// <summary>
        /// Gets or sets FileName.
        /// </summary>
        [JsonProperty("fileName", NullValueHandling = NullValueHandling.Ignore)]
        public string FileName { get; set; }

        /// <summary>
        /// Gets or sets ContentId.
        /// </summary>
        [JsonProperty("contentId", NullValueHandling = NullValueHandling.Ignore)]
        public string ContentId { get; set; }

        /// <summary>
        /// Gets or sets InvoiceType.
        /// </summary>
        [JsonProperty("invoiceType", NullValueHandling = NullValueHandling.Ignore)]
        public string InvoiceType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargingInvoice : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargingInvoice other &&
                (this.FileName == null && other.FileName == null ||
                 this.FileName?.Equals(other.FileName) == true) &&
                (this.ContentId == null && other.ContentId == null ||
                 this.ContentId?.Equals(other.ContentId) == true) &&
                (this.InvoiceType == null && other.InvoiceType == null ||
                 this.InvoiceType?.Equals(other.InvoiceType) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"FileName = {this.FileName ?? "null"}");
            toStringOutput.Add($"ContentId = {this.ContentId ?? "null"}");
            toStringOutput.Add($"InvoiceType = {this.InvoiceType ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}