// <copyright file="ChargeHistory.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ChargeHistory.
    /// </summary>
    public class ChargeHistory
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargeHistory"/> class.
        /// </summary>
        public ChargeHistory()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargeHistory"/> class.
        /// </summary>
        /// <param name="chargeStartTime">charge_start_time.</param>
        /// <param name="chargeDuration">charge_duration.</param>
        /// <param name="energyAddedWh">energy_added_wh.</param>
        public ChargeHistory(
            Models.ChargeStartTime chargeStartTime,
            Models.ChargeDuration chargeDuration,
            int energyAddedWh)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ChargeStartTime = chargeStartTime;
            this.ChargeDuration = chargeDuration;
            this.EnergyAddedWh = energyAddedWh;
        }

        /// <summary>
        /// Gets or sets ChargeStartTime.
        /// </summary>
        [JsonProperty("charge_start_time")]
        public Models.ChargeStartTime ChargeStartTime { get; set; }

        /// <summary>
        /// Gets or sets ChargeDuration.
        /// </summary>
        [JsonProperty("charge_duration")]
        public Models.ChargeDuration ChargeDuration { get; set; }

        /// <summary>
        /// Gets or sets EnergyAddedWh.
        /// </summary>
        [JsonProperty("energy_added_wh")]
        public int EnergyAddedWh { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargeHistory : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargeHistory other &&
                (this.ChargeStartTime == null && other.ChargeStartTime == null ||
                 this.ChargeStartTime?.Equals(other.ChargeStartTime) == true) &&
                (this.ChargeDuration == null && other.ChargeDuration == null ||
                 this.ChargeDuration?.Equals(other.ChargeDuration) == true) &&
                (this.EnergyAddedWh.Equals(other.EnergyAddedWh)) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ChargeStartTime = {(this.ChargeStartTime == null ? "null" : this.ChargeStartTime.ToString())}");
            toStringOutput.Add($"ChargeDuration = {(this.ChargeDuration == null ? "null" : this.ChargeDuration.ToString())}");
            toStringOutput.Add($"EnergyAddedWh = {this.EnergyAddedWh}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}