// <copyright file="ChargingSession.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ChargingSession.
    /// </summary>
    public class ChargingSession
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingSession"/> class.
        /// </summary>
        public ChargingSession()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingSession"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="vin">vin.</param>
        /// <param name="model">model.</param>
        /// <param name="startDateTime">start_date_time.</param>
        /// <param name="stopDateTime">stop_date_time.</param>
        /// <param name="totalEnergy">total_energy.</param>
        /// <param name="totalTime">total_time.</param>
        /// <param name="totalCost">total_cost.</param>
        /// <param name="location">location.</param>
        /// <param name="chargingPeriods">charging_periods.</param>
        /// <param name="tariffs">tariffs.</param>
        public ChargingSession(
            string id = null,
            string vin = null,
            string model = null,
            string startDateTime = null,
            string stopDateTime = null,
            double? totalEnergy = null,
            double? totalTime = null,
            Models.TotalCost totalCost = null,
            Models.Location location = null,
            List<Models.ChargingPeriod> chargingPeriods = null,
            Models.Tariffs tariffs = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.Vin = vin;
            this.Model = model;
            this.StartDateTime = startDateTime;
            this.StopDateTime = stopDateTime;
            this.TotalEnergy = totalEnergy;
            this.TotalTime = totalTime;
            this.TotalCost = totalCost;
            this.Location = location;
            this.ChargingPeriods = chargingPeriods;
            this.Tariffs = tariffs;
        }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or sets Vin.
        /// </summary>
        [JsonProperty("vin", NullValueHandling = NullValueHandling.Ignore)]
        public string Vin { get; set; }

        /// <summary>
        /// Gets or sets Model.
        /// </summary>
        [JsonProperty("model", NullValueHandling = NullValueHandling.Ignore)]
        public string Model { get; set; }

        /// <summary>
        /// Gets or sets StartDateTime.
        /// </summary>
        [JsonProperty("start_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string StartDateTime { get; set; }

        /// <summary>
        /// Gets or sets StopDateTime.
        /// </summary>
        [JsonProperty("stop_date_time", NullValueHandling = NullValueHandling.Ignore)]
        public string StopDateTime { get; set; }

        /// <summary>
        /// Gets or sets TotalEnergy.
        /// </summary>
        [JsonProperty("total_energy", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalEnergy { get; set; }

        /// <summary>
        /// Gets or sets TotalTime.
        /// </summary>
        [JsonProperty("total_time", NullValueHandling = NullValueHandling.Ignore)]
        public double? TotalTime { get; set; }

        /// <summary>
        /// Gets or sets TotalCost.
        /// </summary>
        [JsonProperty("total_cost", NullValueHandling = NullValueHandling.Ignore)]
        public Models.TotalCost TotalCost { get; set; }

        /// <summary>
        /// Gets or sets Location.
        /// </summary>
        [JsonProperty("location", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Location Location { get; set; }

        /// <summary>
        /// Gets or sets ChargingPeriods.
        /// </summary>
        [JsonProperty("charging_periods", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ChargingPeriod> ChargingPeriods { get; set; }

        /// <summary>
        /// Gets or sets Tariffs.
        /// </summary>
        [JsonProperty("tariffs", NullValueHandling = NullValueHandling.Ignore)]
        public Models.Tariffs Tariffs { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargingSession : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargingSession other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.Vin == null && other.Vin == null ||
                 this.Vin?.Equals(other.Vin) == true) &&
                (this.Model == null && other.Model == null ||
                 this.Model?.Equals(other.Model) == true) &&
                (this.StartDateTime == null && other.StartDateTime == null ||
                 this.StartDateTime?.Equals(other.StartDateTime) == true) &&
                (this.StopDateTime == null && other.StopDateTime == null ||
                 this.StopDateTime?.Equals(other.StopDateTime) == true) &&
                (this.TotalEnergy == null && other.TotalEnergy == null ||
                 this.TotalEnergy?.Equals(other.TotalEnergy) == true) &&
                (this.TotalTime == null && other.TotalTime == null ||
                 this.TotalTime?.Equals(other.TotalTime) == true) &&
                (this.TotalCost == null && other.TotalCost == null ||
                 this.TotalCost?.Equals(other.TotalCost) == true) &&
                (this.Location == null && other.Location == null ||
                 this.Location?.Equals(other.Location) == true) &&
                (this.ChargingPeriods == null && other.ChargingPeriods == null ||
                 this.ChargingPeriods?.Equals(other.ChargingPeriods) == true) &&
                (this.Tariffs == null && other.Tariffs == null ||
                 this.Tariffs?.Equals(other.Tariffs) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {this.Id ?? "null"}");
            toStringOutput.Add($"Vin = {this.Vin ?? "null"}");
            toStringOutput.Add($"Model = {this.Model ?? "null"}");
            toStringOutput.Add($"StartDateTime = {this.StartDateTime ?? "null"}");
            toStringOutput.Add($"StopDateTime = {this.StopDateTime ?? "null"}");
            toStringOutput.Add($"TotalEnergy = {(this.TotalEnergy == null ? "null" : this.TotalEnergy.ToString())}");
            toStringOutput.Add($"TotalTime = {(this.TotalTime == null ? "null" : this.TotalTime.ToString())}");
            toStringOutput.Add($"TotalCost = {(this.TotalCost == null ? "null" : this.TotalCost.ToString())}");
            toStringOutput.Add($"Location = {(this.Location == null ? "null" : this.Location.ToString())}");
            toStringOutput.Add($"ChargingPeriods = {(this.ChargingPeriods == null ? "null" : $"[{string.Join(", ", this.ChargingPeriods)} ]")}");
            toStringOutput.Add($"Tariffs = {(this.Tariffs == null ? "null" : this.Tariffs.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}