// <copyright file="ChargingHistoryItem.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ChargingHistoryItem.
    /// </summary>
    public class ChargingHistoryItem
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingHistoryItem"/> class.
        /// </summary>
        public ChargingHistoryItem()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ChargingHistoryItem"/> class.
        /// </summary>
        /// <param name="sessionId">sessionId.</param>
        /// <param name="vin">vin.</param>
        /// <param name="siteLocationName">siteLocationName.</param>
        /// <param name="chargeStartDateTime">chargeStartDateTime.</param>
        /// <param name="chargeStopDateTime">chargeStopDateTime.</param>
        /// <param name="unlatchDateTime">unlatchDateTime.</param>
        /// <param name="countryCode">countryCode.</param>
        /// <param name="fees">fees.</param>
        /// <param name="billingType">billingType.</param>
        /// <param name="invoices">invoices.</param>
        /// <param name="vehicleMakeType">vehicleMakeType.</param>
        public ChargingHistoryItem(
            int sessionId,
            string vin,
            string siteLocationName = null,
            DateTime? chargeStartDateTime = null,
            DateTime? chargeStopDateTime = null,
            DateTime? unlatchDateTime = null,
            string countryCode = null,
            List<Models.ChargingFee> fees = null,
            string billingType = null,
            List<Models.ChargingInvoice> invoices = null,
            string vehicleMakeType = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.SessionId = sessionId;
            this.Vin = vin;
            this.SiteLocationName = siteLocationName;
            this.ChargeStartDateTime = chargeStartDateTime;
            this.ChargeStopDateTime = chargeStopDateTime;
            this.UnlatchDateTime = unlatchDateTime;
            this.CountryCode = countryCode;
            this.Fees = fees;
            this.BillingType = billingType;
            this.Invoices = invoices;
            this.VehicleMakeType = vehicleMakeType;
        }

        /// <summary>
        /// Gets or sets SessionId.
        /// </summary>
        [JsonProperty("sessionId")]
        public int SessionId { get; set; }

        /// <summary>
        /// Gets or sets Vin.
        /// </summary>
        [JsonProperty("vin")]
        public string Vin { get; set; }

        /// <summary>
        /// Gets or sets SiteLocationName.
        /// </summary>
        [JsonProperty("siteLocationName", NullValueHandling = NullValueHandling.Ignore)]
        public string SiteLocationName { get; set; }

        /// <summary>
        /// Gets or sets ChargeStartDateTime.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("chargeStartDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? ChargeStartDateTime { get; set; }

        /// <summary>
        /// Gets or sets ChargeStopDateTime.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("chargeStopDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? ChargeStopDateTime { get; set; }

        /// <summary>
        /// Gets or sets UnlatchDateTime.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("unlatchDateTime", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? UnlatchDateTime { get; set; }

        /// <summary>
        /// Gets or sets CountryCode.
        /// </summary>
        [JsonProperty("countryCode", NullValueHandling = NullValueHandling.Ignore)]
        public string CountryCode { get; set; }

        /// <summary>
        /// Gets or sets Fees.
        /// </summary>
        [JsonProperty("fees", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ChargingFee> Fees { get; set; }

        /// <summary>
        /// Gets or sets BillingType.
        /// </summary>
        [JsonProperty("billingType", NullValueHandling = NullValueHandling.Ignore)]
        public string BillingType { get; set; }

        /// <summary>
        /// Gets or sets Invoices.
        /// </summary>
        [JsonProperty("invoices", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ChargingInvoice> Invoices { get; set; }

        /// <summary>
        /// Gets or sets VehicleMakeType.
        /// </summary>
        [JsonProperty("vehicleMakeType", NullValueHandling = NullValueHandling.Ignore)]
        public string VehicleMakeType { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ChargingHistoryItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ChargingHistoryItem other &&
                (this.SessionId.Equals(other.SessionId)) &&
                (this.Vin == null && other.Vin == null ||
                 this.Vin?.Equals(other.Vin) == true) &&
                (this.SiteLocationName == null && other.SiteLocationName == null ||
                 this.SiteLocationName?.Equals(other.SiteLocationName) == true) &&
                (this.ChargeStartDateTime == null && other.ChargeStartDateTime == null ||
                 this.ChargeStartDateTime?.Equals(other.ChargeStartDateTime) == true) &&
                (this.ChargeStopDateTime == null && other.ChargeStopDateTime == null ||
                 this.ChargeStopDateTime?.Equals(other.ChargeStopDateTime) == true) &&
                (this.UnlatchDateTime == null && other.UnlatchDateTime == null ||
                 this.UnlatchDateTime?.Equals(other.UnlatchDateTime) == true) &&
                (this.CountryCode == null && other.CountryCode == null ||
                 this.CountryCode?.Equals(other.CountryCode) == true) &&
                (this.Fees == null && other.Fees == null ||
                 this.Fees?.Equals(other.Fees) == true) &&
                (this.BillingType == null && other.BillingType == null ||
                 this.BillingType?.Equals(other.BillingType) == true) &&
                (this.Invoices == null && other.Invoices == null ||
                 this.Invoices?.Equals(other.Invoices) == true) &&
                (this.VehicleMakeType == null && other.VehicleMakeType == null ||
                 this.VehicleMakeType?.Equals(other.VehicleMakeType) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"SessionId = {this.SessionId}");
            toStringOutput.Add($"Vin = {this.Vin ?? "null"}");
            toStringOutput.Add($"SiteLocationName = {this.SiteLocationName ?? "null"}");
            toStringOutput.Add($"ChargeStartDateTime = {(this.ChargeStartDateTime == null ? "null" : this.ChargeStartDateTime.ToString())}");
            toStringOutput.Add($"ChargeStopDateTime = {(this.ChargeStopDateTime == null ? "null" : this.ChargeStopDateTime.ToString())}");
            toStringOutput.Add($"UnlatchDateTime = {(this.UnlatchDateTime == null ? "null" : this.UnlatchDateTime.ToString())}");
            toStringOutput.Add($"CountryCode = {this.CountryCode ?? "null"}");
            toStringOutput.Add($"Fees = {(this.Fees == null ? "null" : $"[{string.Join(", ", this.Fees)} ]")}");
            toStringOutput.Add($"BillingType = {this.BillingType ?? "null"}");
            toStringOutput.Add($"Invoices = {(this.Invoices == null ? "null" : $"[{string.Join(", ", this.Invoices)} ]")}");
            toStringOutput.Add($"VehicleMakeType = {this.VehicleMakeType ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}