// <copyright file="DefaultRealMode.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// DefaultRealMode.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum DefaultRealMode
    {
        /// <summary>
        /// Autonomous.
        /// </summary>
        [EnumMember(Value = "autonomous")]
        Autonomous,

        /// <summary>
        /// SelfConsumption.
        /// </summary>
        [EnumMember(Value = "self_consumption")]
        SelfConsumption,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}