// <copyright file="Driver.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// Driver.
    /// </summary>
    public class Driver
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Driver"/> class.
        /// </summary>
        public Driver()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Driver"/> class.
        /// </summary>
        /// <param name="myTeslaUniqueId">my_tesla_unique_id.</param>
        /// <param name="userId">user_id.</param>
        /// <param name="userIdS">user_id_s.</param>
        /// <param name="vaultUuid">vault_uuid.</param>
        /// <param name="driverFirstName">driver_first_name.</param>
        /// <param name="driverLastName">driver_last_name.</param>
        /// <param name="granularAccess">granular_access.</param>
        /// <param name="activePubkeys">active_pubkeys.</param>
        /// <param name="publicKey">public_key.</param>
        public Driver(
            int? myTeslaUniqueId = null,
            int? userId = null,
            string userIdS = null,
            string vaultUuid = null,
            string driverFirstName = null,
            string driverLastName = null,
            object granularAccess = null,
            List<string> activePubkeys = null,
            string publicKey = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.MyTeslaUniqueId = myTeslaUniqueId;
            this.UserId = userId;
            this.UserIdS = userIdS;
            this.VaultUuid = vaultUuid;
            this.DriverFirstName = driverFirstName;
            this.DriverLastName = driverLastName;
            this.GranularAccess = granularAccess;
            this.ActivePubkeys = activePubkeys;
            this.PublicKey = publicKey;
        }

        /// <summary>
        /// Gets or sets MyTeslaUniqueId.
        /// </summary>
        [JsonProperty("my_tesla_unique_id", NullValueHandling = NullValueHandling.Ignore)]
        public int? MyTeslaUniqueId { get; set; }

        /// <summary>
        /// Gets or sets UserId.
        /// </summary>
        [JsonProperty("user_id", NullValueHandling = NullValueHandling.Ignore)]
        public int? UserId { get; set; }

        /// <summary>
        /// Gets or sets UserIdS.
        /// </summary>
        [JsonProperty("user_id_s", NullValueHandling = NullValueHandling.Ignore)]
        public string UserIdS { get; set; }

        /// <summary>
        /// Gets or sets VaultUuid.
        /// </summary>
        [JsonProperty("vault_uuid", NullValueHandling = NullValueHandling.Ignore)]
        public string VaultUuid { get; set; }

        /// <summary>
        /// Gets or sets DriverFirstName.
        /// </summary>
        [JsonProperty("driver_first_name", NullValueHandling = NullValueHandling.Ignore)]
        public string DriverFirstName { get; set; }

        /// <summary>
        /// Gets or sets DriverLastName.
        /// </summary>
        [JsonProperty("driver_last_name", NullValueHandling = NullValueHandling.Ignore)]
        public string DriverLastName { get; set; }

        /// <summary>
        /// Gets or sets GranularAccess.
        /// </summary>
        [JsonProperty("granular_access", NullValueHandling = NullValueHandling.Ignore)]
        public object GranularAccess { get; set; }

        /// <summary>
        /// Gets or sets ActivePubkeys.
        /// </summary>
        [JsonProperty("active_pubkeys", NullValueHandling = NullValueHandling.Ignore)]
        public List<string> ActivePubkeys { get; set; }

        /// <summary>
        /// Gets or sets PublicKey.
        /// </summary>
        [JsonProperty("public_key", NullValueHandling = NullValueHandling.Ignore)]
        public string PublicKey { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Driver : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Driver other &&
                (this.MyTeslaUniqueId == null && other.MyTeslaUniqueId == null ||
                 this.MyTeslaUniqueId?.Equals(other.MyTeslaUniqueId) == true) &&
                (this.UserId == null && other.UserId == null ||
                 this.UserId?.Equals(other.UserId) == true) &&
                (this.UserIdS == null && other.UserIdS == null ||
                 this.UserIdS?.Equals(other.UserIdS) == true) &&
                (this.VaultUuid == null && other.VaultUuid == null ||
                 this.VaultUuid?.Equals(other.VaultUuid) == true) &&
                (this.DriverFirstName == null && other.DriverFirstName == null ||
                 this.DriverFirstName?.Equals(other.DriverFirstName) == true) &&
                (this.DriverLastName == null && other.DriverLastName == null ||
                 this.DriverLastName?.Equals(other.DriverLastName) == true) &&
                (this.GranularAccess == null && other.GranularAccess == null ||
                 this.GranularAccess?.Equals(other.GranularAccess) == true) &&
                (this.ActivePubkeys == null && other.ActivePubkeys == null ||
                 this.ActivePubkeys?.Equals(other.ActivePubkeys) == true) &&
                (this.PublicKey == null && other.PublicKey == null ||
                 this.PublicKey?.Equals(other.PublicKey) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"MyTeslaUniqueId = {(this.MyTeslaUniqueId == null ? "null" : this.MyTeslaUniqueId.ToString())}");
            toStringOutput.Add($"UserId = {(this.UserId == null ? "null" : this.UserId.ToString())}");
            toStringOutput.Add($"UserIdS = {this.UserIdS ?? "null"}");
            toStringOutput.Add($"VaultUuid = {this.VaultUuid ?? "null"}");
            toStringOutput.Add($"DriverFirstName = {this.DriverFirstName ?? "null"}");
            toStringOutput.Add($"DriverLastName = {this.DriverLastName ?? "null"}");
            toStringOutput.Add($"GranularAccess = {(this.GranularAccess == null ? "null" : this.GranularAccess.ToString())}");
            toStringOutput.Add($"ActivePubkeys = {(this.ActivePubkeys == null ? "null" : $"[{string.Join(", ", this.ActivePubkeys)} ]")}");
            toStringOutput.Add($"PublicKey = {this.PublicKey ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}