// <copyright file="Kind.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// Kind.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum Kind
    {
        /// <summary>
        /// Backup.
        /// </summary>
        [EnumMember(Value = "backup")]
        Backup,

        /// <summary>
        /// Energy.
        /// </summary>
        [EnumMember(Value = "energy")]
        Energy,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}