// <copyright file="OAuthScopeThirdpartytoken.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Runtime.Serialization;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// OAuthScopeThirdpartytoken.
    /// </summary>

    [JsonConverter(typeof(StringEnumConverter))]
    public enum OAuthScopeThirdpartytoken
    {
        /// <summary>
        ///Allow Tesla customers to sign in to the application with their Tesla credentials.
        /// Openid.
        /// </summary>
        [EnumMember(Value = "openid")]
        Openid,

        /// <summary>
        ///Allow getting a refresh token without needing user to log in again.
        /// OfflineAccess.
        /// </summary>
        [EnumMember(Value = "offline_access")]
        OfflineAccess,

        /// <summary>
        ///Contact information, home address, profile picture, and referral information.
        /// UserData.
        /// </summary>
        [EnumMember(Value = "user_data")]
        UserData,

        /// <summary>
        ///Allow access to your vehicle’s live data, service history, service scheduling data, service communications, eligible upgrades, nearby Superchargers and ownership details.
        /// VehicleDeviceData.
        /// </summary>
        [EnumMember(Value = "vehicle_device_data")]
        VehicleDeviceData,

        /// <summary>
        ///Allow access to vehicle location information, including precise and coarse location data.
        /// VehicleLocation.
        /// </summary>
        [EnumMember(Value = "vehicle_location")]
        VehicleLocation,

        /// <summary>
        ///Commands like add/remove driver, access Live Camera, unlock, wake up, remote start, and schedule software updates.
        /// VehicleCmds.
        /// </summary>
        [EnumMember(Value = "vehicle_cmds")]
        VehicleCmds,

        /// <summary>
        ///Vehicle charging history, billed amount, charging location, and commands to schedule, start, or stop charging.
        /// VehicleChargingCmds.
        /// </summary>
        [EnumMember(Value = "vehicle_charging_cmds")]
        VehicleChargingCmds,

        /// <summary>
        ///Access detailed vehicle specifications. Partner tokens only; usable without owner authorization.
        /// VehicleSpecs.
        /// </summary>
        [EnumMember(Value = "vehicle_specs")]
        VehicleSpecs,

        /// <summary>
        ///Energy live status, site info, backup history, energy history, and charge history.
        /// EnergyDeviceData.
        /// </summary>
        [EnumMember(Value = "energy_device_data")]
        EnergyDeviceData,

        /// <summary>
        ///Update energy settings like backup reserve percent, operation mode, and storm mode.
        /// EnergyCmds.
        /// </summary>
        [EnumMember(Value = "energy_cmds")]
        EnergyCmds,

        /// <summary>
        ///Allow access to enterprise management functions for businesses.
        /// EnterpriseManagement.
        /// </summary>
        [EnumMember(Value = "enterprise_management")]
        EnterpriseManagement
    }

    internal static class OAuthScopeThirdpartytokenExtensions
    {
        internal static string GetValues(this IEnumerable<OAuthScopeThirdpartytoken> values) => values != null
            ? string.Join(" ", values.Select(s => s.GetValue()).Where(s => !string.IsNullOrEmpty(s)).ToArray())
            : null;

        private static string GetValue(this Enum value) =>
            value.GetType()
                .GetTypeInfo()
                .DeclaredMembers
                .SingleOrDefault(x => x.Name == value.ToString())
                ?.GetCustomAttribute<EnumMemberAttribute>(false)
                ?.Value;
    }
}