// <copyright file="Pagination.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// Pagination.
    /// </summary>
    public class Pagination
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private int? previous;
        private int? next;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "previous", false },
            { "next", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="Pagination"/> class.
        /// </summary>
        public Pagination()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Pagination"/> class.
        /// </summary>
        /// <param name="previous">previous.</param>
        /// <param name="next">next.</param>
        /// <param name="current">current.</param>
        /// <param name="perPage">per_page.</param>
        /// <param name="count">count.</param>
        /// <param name="pages">pages.</param>
        public Pagination(
            int? previous = null,
            int? next = null,
            int? current = null,
            int? perPage = null,
            int? count = null,
            int? pages = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();

            if (previous != null)
            {
                this.Previous = previous;
            }

            if (next != null)
            {
                this.Next = next;
            }
            this.Current = current;
            this.PerPage = perPage;
            this.Count = count;
            this.Pages = pages;
        }

        /// <summary>
        /// Gets or sets Previous.
        /// </summary>
        [JsonProperty("previous")]
        public int? Previous
        {
            get
            {
                return this.previous;
            }

            set
            {
                this.shouldSerialize["previous"] = true;
                this.previous = value;
            }
        }

        /// <summary>
        /// Gets or sets Next.
        /// </summary>
        [JsonProperty("next")]
        public int? Next
        {
            get
            {
                return this.next;
            }

            set
            {
                this.shouldSerialize["next"] = true;
                this.next = value;
            }
        }

        /// <summary>
        /// Gets or sets Current.
        /// </summary>
        [JsonProperty("current", NullValueHandling = NullValueHandling.Ignore)]
        public int? Current { get; set; }

        /// <summary>
        /// Gets or sets PerPage.
        /// </summary>
        [JsonProperty("per_page", NullValueHandling = NullValueHandling.Ignore)]
        public int? PerPage { get; set; }

        /// <summary>
        /// Gets or sets Count.
        /// </summary>
        [JsonProperty("count", NullValueHandling = NullValueHandling.Ignore)]
        public int? Count { get; set; }

        /// <summary>
        /// Gets or sets Pages.
        /// </summary>
        [JsonProperty("pages", NullValueHandling = NullValueHandling.Ignore)]
        public int? Pages { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Pagination : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetPrevious()
        {
            this.shouldSerialize["previous"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetNext()
        {
            this.shouldSerialize["next"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializePrevious()
        {
            return this.shouldSerialize["previous"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeNext()
        {
            return this.shouldSerialize["next"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Pagination other &&
                (this.Previous == null && other.Previous == null ||
                 this.Previous?.Equals(other.Previous) == true) &&
                (this.Next == null && other.Next == null ||
                 this.Next?.Equals(other.Next) == true) &&
                (this.Current == null && other.Current == null ||
                 this.Current?.Equals(other.Current) == true) &&
                (this.PerPage == null && other.PerPage == null ||
                 this.PerPage?.Equals(other.PerPage) == true) &&
                (this.Count == null && other.Count == null ||
                 this.Count?.Equals(other.Count) == true) &&
                (this.Pages == null && other.Pages == null ||
                 this.Pages?.Equals(other.Pages) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Previous = {(this.Previous == null ? "null" : this.Previous.ToString())}");
            toStringOutput.Add($"Next = {(this.Next == null ? "null" : this.Next.ToString())}");
            toStringOutput.Add($"Current = {(this.Current == null ? "null" : this.Current.ToString())}");
            toStringOutput.Add($"PerPage = {(this.PerPage == null ? "null" : this.PerPage.ToString())}");
            toStringOutput.Add($"Count = {(this.Count == null ? "null" : this.Count.ToString())}");
            toStringOutput.Add($"Pages = {(this.Pages == null ? "null" : this.Pages.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}