// <copyright file="ResponseRegisterPartnerResponse.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ResponseRegisterPartnerResponse.
    /// </summary>
    public class ResponseRegisterPartnerResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string ca;
        private string issuer;
        private string csr;
        private DateTime? csrUpdatedAt;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "ca", false },
            { "issuer", false },
            { "csr", false },
            { "csr_updated_at", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseRegisterPartnerResponse"/> class.
        /// </summary>
        public ResponseRegisterPartnerResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseRegisterPartnerResponse"/> class.
        /// </summary>
        /// <param name="clientId">client_id.</param>
        /// <param name="name">name.</param>
        /// <param name="domain">domain.</param>
        /// <param name="createdAt">created_at.</param>
        /// <param name="updatedAt">updated_at.</param>
        /// <param name="enterpriseTier">enterprise_tier.</param>
        /// <param name="accountId">account_id.</param>
        /// <param name="publicKey">public_key.</param>
        /// <param name="publicKeyHash">public_key_hash.</param>
        /// <param name="description">description.</param>
        /// <param name="ca">ca.</param>
        /// <param name="issuer">issuer.</param>
        /// <param name="csr">csr.</param>
        /// <param name="csrUpdatedAt">csr_updated_at.</param>
        public ResponseRegisterPartnerResponse(
            string clientId,
            string name,
            string domain,
            DateTime createdAt,
            DateTime updatedAt,
            string enterpriseTier,
            string accountId,
            string publicKey,
            string publicKeyHash,
            string description = null,
            string ca = null,
            string issuer = null,
            string csr = null,
            DateTime? csrUpdatedAt = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ClientId = clientId;
            this.Name = name;
            this.Description = description;
            this.Domain = domain;

            if (ca != null)
            {
                this.Ca = ca;
            }
            this.CreatedAt = createdAt;
            this.UpdatedAt = updatedAt;
            this.EnterpriseTier = enterpriseTier;
            this.AccountId = accountId;

            if (issuer != null)
            {
                this.Issuer = issuer;
            }

            if (csr != null)
            {
                this.Csr = csr;
            }

            if (csrUpdatedAt != null)
            {
                this.CsrUpdatedAt = csrUpdatedAt;
            }
            this.PublicKey = publicKey;
            this.PublicKeyHash = publicKeyHash;
        }

        /// <summary>
        /// Gets or sets ClientId.
        /// </summary>
        [JsonProperty("client_id")]
        public string ClientId { get; set; }

        /// <summary>
        /// Gets or sets Name.
        /// </summary>
        [JsonProperty("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or sets Description.
        /// </summary>
        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }

        /// <summary>
        /// Gets or sets Domain.
        /// </summary>
        [JsonProperty("domain")]
        public string Domain { get; set; }

        /// <summary>
        /// Gets or sets Ca.
        /// </summary>
        [JsonProperty("ca")]
        public string Ca
        {
            get
            {
                return this.ca;
            }

            set
            {
                this.shouldSerialize["ca"] = true;
                this.ca = value;
            }
        }

        /// <summary>
        /// Gets or sets CreatedAt.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or sets UpdatedAt.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("updated_at")]
        public DateTime UpdatedAt { get; set; }

        /// <summary>
        /// Gets or sets EnterpriseTier.
        /// </summary>
        [JsonProperty("enterprise_tier")]
        public string EnterpriseTier { get; set; }

        /// <summary>
        /// Gets or sets AccountId.
        /// </summary>
        [JsonProperty("account_id")]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or sets Issuer.
        /// </summary>
        [JsonProperty("issuer")]
        public string Issuer
        {
            get
            {
                return this.issuer;
            }

            set
            {
                this.shouldSerialize["issuer"] = true;
                this.issuer = value;
            }
        }

        /// <summary>
        /// Gets or sets Csr.
        /// </summary>
        [JsonProperty("csr")]
        public string Csr
        {
            get
            {
                return this.csr;
            }

            set
            {
                this.shouldSerialize["csr"] = true;
                this.csr = value;
            }
        }

        /// <summary>
        /// Gets or sets CsrUpdatedAt.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("csr_updated_at")]
        public DateTime? CsrUpdatedAt
        {
            get
            {
                return this.csrUpdatedAt;
            }

            set
            {
                this.shouldSerialize["csr_updated_at"] = true;
                this.csrUpdatedAt = value;
            }
        }

        /// <summary>
        /// Gets or sets PublicKey.
        /// </summary>
        [JsonProperty("public_key")]
        public string PublicKey { get; set; }

        /// <summary>
        /// Gets or sets PublicKeyHash.
        /// </summary>
        [JsonProperty("public_key_hash")]
        public string PublicKeyHash { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ResponseRegisterPartnerResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCa()
        {
            this.shouldSerialize["ca"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetIssuer()
        {
            this.shouldSerialize["issuer"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCsr()
        {
            this.shouldSerialize["csr"] = false;
        }
        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetCsrUpdatedAt()
        {
            this.shouldSerialize["csr_updated_at"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCa()
        {
            return this.shouldSerialize["ca"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeIssuer()
        {
            return this.shouldSerialize["issuer"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCsr()
        {
            return this.shouldSerialize["csr"];
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeCsrUpdatedAt()
        {
            return this.shouldSerialize["csr_updated_at"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ResponseRegisterPartnerResponse other &&
                (this.ClientId == null && other.ClientId == null ||
                 this.ClientId?.Equals(other.ClientId) == true) &&
                (this.Name == null && other.Name == null ||
                 this.Name?.Equals(other.Name) == true) &&
                (this.Description == null && other.Description == null ||
                 this.Description?.Equals(other.Description) == true) &&
                (this.Domain == null && other.Domain == null ||
                 this.Domain?.Equals(other.Domain) == true) &&
                (this.Ca == null && other.Ca == null ||
                 this.Ca?.Equals(other.Ca) == true) &&
                (this.CreatedAt.Equals(other.CreatedAt)) &&
                (this.UpdatedAt.Equals(other.UpdatedAt)) &&
                (this.EnterpriseTier == null && other.EnterpriseTier == null ||
                 this.EnterpriseTier?.Equals(other.EnterpriseTier) == true) &&
                (this.AccountId == null && other.AccountId == null ||
                 this.AccountId?.Equals(other.AccountId) == true) &&
                (this.Issuer == null && other.Issuer == null ||
                 this.Issuer?.Equals(other.Issuer) == true) &&
                (this.Csr == null && other.Csr == null ||
                 this.Csr?.Equals(other.Csr) == true) &&
                (this.CsrUpdatedAt == null && other.CsrUpdatedAt == null ||
                 this.CsrUpdatedAt?.Equals(other.CsrUpdatedAt) == true) &&
                (this.PublicKey == null && other.PublicKey == null ||
                 this.PublicKey?.Equals(other.PublicKey) == true) &&
                (this.PublicKeyHash == null && other.PublicKeyHash == null ||
                 this.PublicKeyHash?.Equals(other.PublicKeyHash) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ClientId = {this.ClientId ?? "null"}");
            toStringOutput.Add($"Name = {this.Name ?? "null"}");
            toStringOutput.Add($"Description = {this.Description ?? "null"}");
            toStringOutput.Add($"Domain = {this.Domain ?? "null"}");
            toStringOutput.Add($"Ca = {this.Ca ?? "null"}");
            toStringOutput.Add($"CreatedAt = {this.CreatedAt}");
            toStringOutput.Add($"UpdatedAt = {this.UpdatedAt}");
            toStringOutput.Add($"EnterpriseTier = {this.EnterpriseTier ?? "null"}");
            toStringOutput.Add($"AccountId = {this.AccountId ?? "null"}");
            toStringOutput.Add($"Issuer = {this.Issuer ?? "null"}");
            toStringOutput.Add($"Csr = {this.Csr ?? "null"}");
            toStringOutput.Add($"CsrUpdatedAt = {(this.CsrUpdatedAt == null ? "null" : this.CsrUpdatedAt.ToString())}");
            toStringOutput.Add($"PublicKey = {this.PublicKey ?? "null"}");
            toStringOutput.Add($"PublicKeyHash = {this.PublicKeyHash ?? "null"}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}