// <copyright file="Response3.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// Response3.
    /// </summary>
    public class Response3
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Response3"/> class.
        /// </summary>
        public Response3()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="Response3"/> class.
        /// </summary>
        /// <param name="destinationCharging">destination_charging.</param>
        /// <param name="superchargers">superchargers.</param>
        /// <param name="timestamp">timestamp.</param>
        public Response3(
            List<Models.ChargingLocation> destinationCharging = null,
            List<Models.ChargingLocation> superchargers = null,
            int? timestamp = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.DestinationCharging = destinationCharging;
            this.Superchargers = superchargers;
            this.Timestamp = timestamp;
        }

        /// <summary>
        /// Gets or sets DestinationCharging.
        /// </summary>
        [JsonProperty("destination_charging", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ChargingLocation> DestinationCharging { get; set; }

        /// <summary>
        /// Gets or sets Superchargers.
        /// </summary>
        [JsonProperty("superchargers", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.ChargingLocation> Superchargers { get; set; }

        /// <summary>
        /// Gets or sets Timestamp.
        /// </summary>
        [JsonProperty("timestamp", NullValueHandling = NullValueHandling.Ignore)]
        public int? Timestamp { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"Response3 : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is Response3 other &&
                (this.DestinationCharging == null && other.DestinationCharging == null ||
                 this.DestinationCharging?.Equals(other.DestinationCharging) == true) &&
                (this.Superchargers == null && other.Superchargers == null ||
                 this.Superchargers?.Equals(other.Superchargers) == true) &&
                (this.Timestamp == null && other.Timestamp == null ||
                 this.Timestamp?.Equals(other.Timestamp) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"DestinationCharging = {(this.DestinationCharging == null ? "null" : $"[{string.Join(", ", this.DestinationCharging)} ]")}");
            toStringOutput.Add($"Superchargers = {(this.Superchargers == null ? "null" : $"[{string.Join(", ", this.Superchargers)} ]")}");
            toStringOutput.Add($"Timestamp = {(this.Timestamp == null ? "null" : this.Timestamp.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}