// <copyright file="ResponseApi1DxWarrantyDetailsResponse.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ResponseApi1DxWarrantyDetailsResponse.
    /// </summary>
    public class ResponseApi1DxWarrantyDetailsResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseApi1DxWarrantyDetailsResponse"/> class.
        /// </summary>
        public ResponseApi1DxWarrantyDetailsResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseApi1DxWarrantyDetailsResponse"/> class.
        /// </summary>
        /// <param name="activeWarranty">activeWarranty.</param>
        /// <param name="upcomingWarranty">upcomingWarranty.</param>
        /// <param name="expiredWarranty">expiredWarranty.</param>
        public ResponseApi1DxWarrantyDetailsResponse(
            List<Models.WarrantyItem> activeWarranty = null,
            List<Models.WarrantyItem> upcomingWarranty = null,
            List<Models.WarrantyItem> expiredWarranty = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ActiveWarranty = activeWarranty;
            this.UpcomingWarranty = upcomingWarranty;
            this.ExpiredWarranty = expiredWarranty;
        }

        /// <summary>
        /// Gets or sets ActiveWarranty.
        /// </summary>
        [JsonProperty("activeWarranty", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.WarrantyItem> ActiveWarranty { get; set; }

        /// <summary>
        /// Gets or sets UpcomingWarranty.
        /// </summary>
        [JsonProperty("upcomingWarranty", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.WarrantyItem> UpcomingWarranty { get; set; }

        /// <summary>
        /// Gets or sets ExpiredWarranty.
        /// </summary>
        [JsonProperty("expiredWarranty", NullValueHandling = NullValueHandling.Ignore)]
        public List<Models.WarrantyItem> ExpiredWarranty { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ResponseApi1DxWarrantyDetailsResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ResponseApi1DxWarrantyDetailsResponse other &&
                (this.ActiveWarranty == null && other.ActiveWarranty == null ||
                 this.ActiveWarranty?.Equals(other.ActiveWarranty) == true) &&
                (this.UpcomingWarranty == null && other.UpcomingWarranty == null ||
                 this.UpcomingWarranty?.Equals(other.UpcomingWarranty) == true) &&
                (this.ExpiredWarranty == null && other.ExpiredWarranty == null ||
                 this.ExpiredWarranty?.Equals(other.ExpiredWarranty) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ActiveWarranty = {(this.ActiveWarranty == null ? "null" : $"[{string.Join(", ", this.ActiveWarranty)} ]")}");
            toStringOutput.Add($"UpcomingWarranty = {(this.UpcomingWarranty == null ? "null" : $"[{string.Join(", ", this.UpcomingWarranty)} ]")}");
            toStringOutput.Add($"ExpiredWarranty = {(this.ExpiredWarranty == null ? "null" : $"[{string.Join(", ", this.ExpiredWarranty)} ]")}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}