// <copyright file="ResponseOrdersResponse.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// ResponseOrdersResponse.
    /// </summary>
    public class ResponseOrdersResponse
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseOrdersResponse"/> class.
        /// </summary>
        public ResponseOrdersResponse()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ResponseOrdersResponse"/> class.
        /// </summary>
        /// <param name="vehicleMapId">vehicleMapId.</param>
        /// <param name="referenceNumber">referenceNumber.</param>
        /// <param name="vin">vin.</param>
        /// <param name="orderStatus">orderStatus.</param>
        /// <param name="orderSubstatus">orderSubstatus.</param>
        /// <param name="modelCode">modelCode.</param>
        /// <param name="countryCode">countryCode.</param>
        /// <param name="locale">locale.</param>
        /// <param name="mktOptions">mktOptions.</param>
        /// <param name="isB2B">isB2b.</param>
        public ResponseOrdersResponse(
            int vehicleMapId,
            string referenceNumber,
            string vin,
            string orderStatus,
            string orderSubstatus,
            string modelCode,
            string countryCode,
            string locale,
            string mktOptions,
            bool isB2B)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.VehicleMapId = vehicleMapId;
            this.ReferenceNumber = referenceNumber;
            this.Vin = vin;
            this.OrderStatus = orderStatus;
            this.OrderSubstatus = orderSubstatus;
            this.ModelCode = modelCode;
            this.CountryCode = countryCode;
            this.Locale = locale;
            this.MktOptions = mktOptions;
            this.IsB2B = isB2B;
        }

        /// <summary>
        /// Gets or sets VehicleMapId.
        /// </summary>
        [JsonProperty("vehicleMapId")]
        public int VehicleMapId { get; set; }

        /// <summary>
        /// Gets or sets ReferenceNumber.
        /// </summary>
        [JsonProperty("referenceNumber")]
        public string ReferenceNumber { get; set; }

        /// <summary>
        /// Gets or sets Vin.
        /// </summary>
        [JsonProperty("vin")]
        public string Vin { get; set; }

        /// <summary>
        /// Gets or sets OrderStatus.
        /// </summary>
        [JsonProperty("orderStatus")]
        public string OrderStatus { get; set; }

        /// <summary>
        /// Gets or sets OrderSubstatus.
        /// </summary>
        [JsonProperty("orderSubstatus")]
        public string OrderSubstatus { get; set; }

        /// <summary>
        /// Gets or sets ModelCode.
        /// </summary>
        [JsonProperty("modelCode")]
        public string ModelCode { get; set; }

        /// <summary>
        /// Gets or sets CountryCode.
        /// </summary>
        [JsonProperty("countryCode")]
        public string CountryCode { get; set; }

        /// <summary>
        /// Gets or sets Locale.
        /// </summary>
        [JsonProperty("locale")]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or sets MktOptions.
        /// </summary>
        [JsonProperty("mktOptions")]
        public string MktOptions { get; set; }

        /// <summary>
        /// Gets or sets IsB2B.
        /// </summary>
        [JsonProperty("isB2b")]
        public bool IsB2B { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"ResponseOrdersResponse : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is ResponseOrdersResponse other &&
                (this.VehicleMapId.Equals(other.VehicleMapId)) &&
                (this.ReferenceNumber == null && other.ReferenceNumber == null ||
                 this.ReferenceNumber?.Equals(other.ReferenceNumber) == true) &&
                (this.Vin == null && other.Vin == null ||
                 this.Vin?.Equals(other.Vin) == true) &&
                (this.OrderStatus == null && other.OrderStatus == null ||
                 this.OrderStatus?.Equals(other.OrderStatus) == true) &&
                (this.OrderSubstatus == null && other.OrderSubstatus == null ||
                 this.OrderSubstatus?.Equals(other.OrderSubstatus) == true) &&
                (this.ModelCode == null && other.ModelCode == null ||
                 this.ModelCode?.Equals(other.ModelCode) == true) &&
                (this.CountryCode == null && other.CountryCode == null ||
                 this.CountryCode?.Equals(other.CountryCode) == true) &&
                (this.Locale == null && other.Locale == null ||
                 this.Locale?.Equals(other.Locale) == true) &&
                (this.MktOptions == null && other.MktOptions == null ||
                 this.MktOptions?.Equals(other.MktOptions) == true) &&
                (this.IsB2B.Equals(other.IsB2B)) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"VehicleMapId = {this.VehicleMapId}");
            toStringOutput.Add($"ReferenceNumber = {this.ReferenceNumber ?? "null"}");
            toStringOutput.Add($"Vin = {this.Vin ?? "null"}");
            toStringOutput.Add($"OrderStatus = {this.OrderStatus ?? "null"}");
            toStringOutput.Add($"OrderSubstatus = {this.OrderSubstatus ?? "null"}");
            toStringOutput.Add($"ModelCode = {this.ModelCode ?? "null"}");
            toStringOutput.Add($"CountryCode = {this.CountryCode ?? "null"}");
            toStringOutput.Add($"Locale = {this.Locale ?? "null"}");
            toStringOutput.Add($"MktOptions = {this.MktOptions ?? "null"}");
            toStringOutput.Add($"IsB2B = {this.IsB2B}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}