// <copyright file="TotalCost.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// TotalCost.
    /// </summary>
    public class TotalCost
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TotalCost"/> class.
        /// </summary>
        public TotalCost()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TotalCost"/> class.
        /// </summary>
        /// <param name="exclVat">excl_vat.</param>
        /// <param name="inclVat">incl_vat.</param>
        /// <param name="vat">vat.</param>
        public TotalCost(
            double? exclVat = null,
            double? inclVat = null,
            double? vat = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.ExclVat = exclVat;
            this.InclVat = inclVat;
            this.Vat = vat;
        }

        /// <summary>
        /// Gets or sets ExclVat.
        /// </summary>
        [JsonProperty("excl_vat", NullValueHandling = NullValueHandling.Ignore)]
        public double? ExclVat { get; set; }

        /// <summary>
        /// Gets or sets InclVat.
        /// </summary>
        [JsonProperty("incl_vat", NullValueHandling = NullValueHandling.Ignore)]
        public double? InclVat { get; set; }

        /// <summary>
        /// Gets or sets Vat.
        /// </summary>
        [JsonProperty("vat", NullValueHandling = NullValueHandling.Ignore)]
        public double? Vat { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"TotalCost : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is TotalCost other &&
                (this.ExclVat == null && other.ExclVat == null ||
                 this.ExclVat?.Equals(other.ExclVat) == true) &&
                (this.InclVat == null && other.InclVat == null ||
                 this.InclVat?.Equals(other.InclVat) == true) &&
                (this.Vat == null && other.Vat == null ||
                 this.Vat?.Equals(other.Vat) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"ExclVat = {(this.ExclVat == null ? "null" : this.ExclVat.ToString())}");
            toStringOutput.Add($"InclVat = {(this.InclVat == null ? "null" : this.InclVat.ToString())}");
            toStringOutput.Add($"Vat = {(this.Vat == null ? "null" : this.Vat.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}