// <copyright file="VehicleBase.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// VehicleBase.
    /// </summary>
    public class VehicleBase
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleBase"/> class.
        /// </summary>
        public VehicleBase()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VehicleBase"/> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="vehicleId">vehicle_id.</param>
        /// <param name="vin">vin.</param>
        /// <param name="displayName">display_name.</param>
        /// <param name="accessType">access_type.</param>
        /// <param name="state">state.</param>
        /// <param name="inService">in_service.</param>
        /// <param name="calendarEnabled">calendar_enabled.</param>
        public VehicleBase(
            int? id = null,
            int? vehicleId = null,
            string vin = null,
            string displayName = null,
            string accessType = null,
            string state = null,
            bool? inService = null,
            bool? calendarEnabled = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.Id = id;
            this.VehicleId = vehicleId;
            this.Vin = vin;
            this.DisplayName = displayName;
            this.AccessType = accessType;
            this.State = state;
            this.InService = inService;
            this.CalendarEnabled = calendarEnabled;
        }

        /// <summary>
        /// Gets or sets Id.
        /// </summary>
        [JsonProperty("id", NullValueHandling = NullValueHandling.Ignore)]
        public int? Id { get; set; }

        /// <summary>
        /// Gets or sets VehicleId.
        /// </summary>
        [JsonProperty("vehicle_id", NullValueHandling = NullValueHandling.Ignore)]
        public int? VehicleId { get; set; }

        /// <summary>
        /// Gets or sets Vin.
        /// </summary>
        [JsonProperty("vin", NullValueHandling = NullValueHandling.Ignore)]
        public string Vin { get; set; }

        /// <summary>
        /// Gets or sets DisplayName.
        /// </summary>
        [JsonProperty("display_name", NullValueHandling = NullValueHandling.Ignore)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or sets AccessType.
        /// </summary>
        [JsonProperty("access_type", NullValueHandling = NullValueHandling.Ignore)]
        public string AccessType { get; set; }

        /// <summary>
        /// Gets or sets State.
        /// </summary>
        [JsonProperty("state", NullValueHandling = NullValueHandling.Ignore)]
        public string State { get; set; }

        /// <summary>
        /// Gets or sets InService.
        /// </summary>
        [JsonProperty("in_service", NullValueHandling = NullValueHandling.Ignore)]
        public bool? InService { get; set; }

        /// <summary>
        /// Gets or sets CalendarEnabled.
        /// </summary>
        [JsonProperty("calendar_enabled", NullValueHandling = NullValueHandling.Ignore)]
        public bool? CalendarEnabled { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"VehicleBase : ({string.Join(", ", toStringOutput)})";
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is VehicleBase other &&
                (this.Id == null && other.Id == null ||
                 this.Id?.Equals(other.Id) == true) &&
                (this.VehicleId == null && other.VehicleId == null ||
                 this.VehicleId?.Equals(other.VehicleId) == true) &&
                (this.Vin == null && other.Vin == null ||
                 this.Vin?.Equals(other.Vin) == true) &&
                (this.DisplayName == null && other.DisplayName == null ||
                 this.DisplayName?.Equals(other.DisplayName) == true) &&
                (this.AccessType == null && other.AccessType == null ||
                 this.AccessType?.Equals(other.AccessType) == true) &&
                (this.State == null && other.State == null ||
                 this.State?.Equals(other.State) == true) &&
                (this.InService == null && other.InService == null ||
                 this.InService?.Equals(other.InService) == true) &&
                (this.CalendarEnabled == null && other.CalendarEnabled == null ||
                 this.CalendarEnabled?.Equals(other.CalendarEnabled) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"Id = {(this.Id == null ? "null" : this.Id.ToString())}");
            toStringOutput.Add($"VehicleId = {(this.VehicleId == null ? "null" : this.VehicleId.ToString())}");
            toStringOutput.Add($"Vin = {this.Vin ?? "null"}");
            toStringOutput.Add($"DisplayName = {this.DisplayName ?? "null"}");
            toStringOutput.Add($"AccessType = {this.AccessType ?? "null"}");
            toStringOutput.Add($"State = {this.State ?? "null"}");
            toStringOutput.Add($"InService = {(this.InService == null ? "null" : this.InService.ToString())}");
            toStringOutput.Add($"CalendarEnabled = {(this.CalendarEnabled == null ? "null" : this.CalendarEnabled.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}