// <copyright file="WarrantyItem.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using TeslaFleetManagementApi.Standard.Utilities;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// WarrantyItem.
    /// </summary>
    public class WarrantyItem
    {
        [JsonExtensionData]
        private readonly IDictionary<string, JToken> additionalProperties;

        private readonly IEnumerable<string> propertyName;

        /// <summary>
        /// Get or set the value associated with the specified key in the AdditionalProperties dictionary.
        /// </summary>
        /// <param name="key">The key of the value to get or set. This must be a valid key that is not reserved for internal properties.</param>
        /// <returns>The object value associated with the specified key in the AdditionalProperties dictionary.</returns>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when <paramref name="key"/> is null or an empty string.
        /// </exception>
        /// <exception cref="System.ArgumentException">
        /// Thrown when the specified <paramref name="key"/> conflicts with an internal property of the object.
        /// </exception>
        /// <exception cref="KeyNotFoundException">
        /// Thrown when the specified <paramref name="key"/> does not exist in the AdditionalProperties dictionary.
        /// </exception>
        [IndexerName("AdditionalPropertiesIndexer")]
        public object this[string key]
        {
            get => additionalProperties.GetValue<object>(key);
            set => additionalProperties.SetValue(key, value, propertyName);
        }

        private string warrantyExpiredOn;
        private Dictionary<string, bool> shouldSerialize = new Dictionary<string, bool>
        {
            { "warrantyExpiredOn", false },
        };

        /// <summary>
        /// Initializes a new instance of the <see cref="WarrantyItem"/> class.
        /// </summary>
        public WarrantyItem()
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WarrantyItem"/> class.
        /// </summary>
        /// <param name="warrantyType">warrantyType.</param>
        /// <param name="warrantyDisplayName">warrantyDisplayName.</param>
        /// <param name="expirationDate">expirationDate.</param>
        /// <param name="expirationOdometer">expirationOdometer.</param>
        /// <param name="odometerUnit">odometerUnit.</param>
        /// <param name="warrantyExpiredOn">warrantyExpiredOn.</param>
        /// <param name="coverageAgeInYears">coverageAgeInYears.</param>
        public WarrantyItem(
            string warrantyType = null,
            string warrantyDisplayName = null,
            DateTime? expirationDate = null,
            int? expirationOdometer = null,
            string odometerUnit = null,
            string warrantyExpiredOn = null,
            int? coverageAgeInYears = null)
        {
            this.additionalProperties = new Dictionary<string, JToken>();
            this.propertyName = this.GetPropertyNames();
            this.WarrantyType = warrantyType;
            this.WarrantyDisplayName = warrantyDisplayName;
            this.ExpirationDate = expirationDate;
            this.ExpirationOdometer = expirationOdometer;
            this.OdometerUnit = odometerUnit;

            if (warrantyExpiredOn != null)
            {
                this.WarrantyExpiredOn = warrantyExpiredOn;
            }
            this.CoverageAgeInYears = coverageAgeInYears;
        }

        /// <summary>
        /// Gets or sets WarrantyType.
        /// </summary>
        [JsonProperty("warrantyType", NullValueHandling = NullValueHandling.Ignore)]
        public string WarrantyType { get; set; }

        /// <summary>
        /// Gets or sets WarrantyDisplayName.
        /// </summary>
        [JsonProperty("warrantyDisplayName", NullValueHandling = NullValueHandling.Ignore)]
        public string WarrantyDisplayName { get; set; }

        /// <summary>
        /// Gets or sets ExpirationDate.
        /// </summary>
        [JsonConverter(typeof(IsoDateTimeConverter))]
        [JsonProperty("expirationDate", NullValueHandling = NullValueHandling.Ignore)]
        public DateTime? ExpirationDate { get; set; }

        /// <summary>
        /// Gets or sets ExpirationOdometer.
        /// </summary>
        [JsonProperty("expirationOdometer", NullValueHandling = NullValueHandling.Ignore)]
        public int? ExpirationOdometer { get; set; }

        /// <summary>
        /// Gets or sets OdometerUnit.
        /// </summary>
        [JsonProperty("odometerUnit", NullValueHandling = NullValueHandling.Ignore)]
        public string OdometerUnit { get; set; }

        /// <summary>
        /// Gets or sets WarrantyExpiredOn.
        /// </summary>
        [JsonProperty("warrantyExpiredOn")]
        public string WarrantyExpiredOn
        {
            get
            {
                return this.warrantyExpiredOn;
            }

            set
            {
                this.shouldSerialize["warrantyExpiredOn"] = true;
                this.warrantyExpiredOn = value;
            }
        }

        /// <summary>
        /// Gets or sets CoverageAgeInYears.
        /// </summary>
        [JsonProperty("coverageAgeInYears", NullValueHandling = NullValueHandling.Ignore)]
        public int? CoverageAgeInYears { get; set; }

        /// <inheritdoc/>
        public override string ToString()
        {
            var toStringOutput = new List<string>();
            this.ToString(toStringOutput);
            return $"WarrantyItem : ({string.Join(", ", toStringOutput)})";
        }

        /// <summary>
        /// Marks the field to not be serialized.
        /// </summary>
        public void UnsetWarrantyExpiredOn()
        {
            this.shouldSerialize["warrantyExpiredOn"] = false;
        }

        /// <summary>
        /// Checks if the field should be serialized or not.
        /// </summary>
        /// <returns>A boolean weather the field should be serialized or not.</returns>
        public bool ShouldSerializeWarrantyExpiredOn()
        {
            return this.shouldSerialize["warrantyExpiredOn"];
        }

        /// <inheritdoc/>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;

            return obj is WarrantyItem other &&
                (this.WarrantyType == null && other.WarrantyType == null ||
                 this.WarrantyType?.Equals(other.WarrantyType) == true) &&
                (this.WarrantyDisplayName == null && other.WarrantyDisplayName == null ||
                 this.WarrantyDisplayName?.Equals(other.WarrantyDisplayName) == true) &&
                (this.ExpirationDate == null && other.ExpirationDate == null ||
                 this.ExpirationDate?.Equals(other.ExpirationDate) == true) &&
                (this.ExpirationOdometer == null && other.ExpirationOdometer == null ||
                 this.ExpirationOdometer?.Equals(other.ExpirationOdometer) == true) &&
                (this.OdometerUnit == null && other.OdometerUnit == null ||
                 this.OdometerUnit?.Equals(other.OdometerUnit) == true) &&
                (this.WarrantyExpiredOn == null && other.WarrantyExpiredOn == null ||
                 this.WarrantyExpiredOn?.Equals(other.WarrantyExpiredOn) == true) &&
                (this.CoverageAgeInYears == null && other.CoverageAgeInYears == null ||
                 this.CoverageAgeInYears?.Equals(other.CoverageAgeInYears) == true) &&
                (this.additionalProperties == null && other.additionalProperties == null ||
                 this.additionalProperties?.Count == other.additionalProperties?.Count &&
                 this.additionalProperties?.All(kv =>
                     other.additionalProperties.TryGetValue(kv.Key, out var value) &&
                     JToken.DeepEquals(kv.Value, value)) == true);
        }

        /// <summary>
        /// ToString overload.
        /// </summary>
        /// <param name="toStringOutput">List of strings.</param>
        protected void ToString(List<string> toStringOutput)
        {
            toStringOutput.Add($"WarrantyType = {this.WarrantyType ?? "null"}");
            toStringOutput.Add($"WarrantyDisplayName = {this.WarrantyDisplayName ?? "null"}");
            toStringOutput.Add($"ExpirationDate = {(this.ExpirationDate == null ? "null" : this.ExpirationDate.ToString())}");
            toStringOutput.Add($"ExpirationOdometer = {(this.ExpirationOdometer == null ? "null" : this.ExpirationOdometer.ToString())}");
            toStringOutput.Add($"OdometerUnit = {this.OdometerUnit ?? "null"}");
            toStringOutput.Add($"WarrantyExpiredOn = {this.WarrantyExpiredOn ?? "null"}");
            toStringOutput.Add($"CoverageAgeInYears = {(this.CoverageAgeInYears == null ? "null" : this.CoverageAgeInYears.ToString())}");

            additionalProperties?
                .Select(kvp => $"[{kvp.Key}] = {kvp.Value.ToString(Formatting.None)}")
                .ToList()
                .ForEach(toStringOutput.Add);
        }
    }
}