// <copyright file="WhichTrunk.cs" company="APIMatic">
// TeslaFleetManagementApi.Standard
//
// This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
// </copyright>
using APIMatic.Core.Utilities.Converters;
using Newtonsoft.Json;
using System.Runtime.Serialization;

namespace TeslaFleetManagementApi.Standard.Models
{
    /// <summary>
    /// WhichTrunk.
    /// </summary>

    [JsonConverter(typeof(UnknownEnumConverter<StringEnumConverter>), nameof(_Unknown))]
    public enum WhichTrunk
    {
        /// <summary>
        /// Front.
        /// </summary>
        [EnumMember(Value = "front")]
        Front,

        /// <summary>
        /// Rear.
        /// </summary>
        [EnumMember(Value = "rear")]
        Rear,

        /// <summary>
        /// Unknown values will be mapped by this enum member.
        /// </summary>
        _Unknown
    }
}